// <auto-generated />
using System;
using FileServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileServer.Migrations
{
    [DbContext(typeof(FileDbContext))]
    [Migration("20260707114929_AddDbComments")]
    partial class AddDbComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileServer.Entities.FileGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BizType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("biztype")
                        .HasComment("비즈니스 구분 (예: PROFILE, BOARD, ITEM 등)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.HasKey("Id");

                    b.ToTable("filegroups", "scom", t =>
                        {
                            t.HasComment("파일 그룹 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("FileServer.Entities.FileMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenttype")
                        .HasComment("Content Type (MIME Type)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<Guid?>("FileGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("filegroupid")
                        .HasComment("파일 그룹 ID (Nullable)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<bool>("IsImage")
                        .HasColumnType("boolean")
                        .HasColumnName("isimage")
                        .HasComment("이미지 파일 여부");

                    b.Property<bool>("IsRepresentative")
                        .HasColumnType("boolean")
                        .HasColumnName("isrepresentative")
                        .HasComment("대표 파일 여부");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("originalname")
                        .HasComment("원본 파일명 (예: photo.png)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path")
                        .HasComment("파일 저장 경로 (디렉토리 상대경로)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size")
                        .HasComment("파일 크기 (Bytes)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sortorder")
                        .HasComment("정렬 순서");

                    b.Property<string>("StoredName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storedname")
                        .HasComment("실제 스토리지에 저장된 파일명 (예: uuid.png)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.HasKey("Id");

                    b.HasIndex("FileGroupId");

                    b.ToTable("filemetadatas", "scom", t =>
                        {
                            t.HasComment("파일의 메타데이터 정보를 저장하는 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("FileServer.Entities.FileMetadata", b =>
                {
                    b.HasOne("FileServer.Entities.FileGroup", "FileGroup")
                        .WithMany("Files")
                        .HasForeignKey("FileGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("FileGroup");
                });

            modelBuilder.Entity("FileServer.Entities.FileGroup", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
