// <auto-generated />
using System;
using FileServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileServer.Migrations
{
    [DbContext(typeof(FileDbContext))]
    [Migration("20260707115451_UpdateAllComments")]
    partial class UpdateAllComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileServer.Entities.FileGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BizType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("biztype")
                        .HasComment("비즈니스 구분 코드 (예: PROFILE, BOARD, ITEM 등)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.HasKey("Id");

                    b.ToTable("filegroups", "scom", t =>
                        {
                            t.HasComment("파일 그룹 엔티티 클래스 (다중 파일 업로드를 그룹 단위로 관리하기 위함)");
                        });
                });

            modelBuilder.Entity("FileServer.Entities.FileMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenttype")
                        .HasComment("HTTP Content-Type (MIME 타입, 예: image/png, application/pdf 등)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<Guid?>("FileGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("filegroupid")
                        .HasComment("소속된 파일 그룹 식별자 (ID, Nullable)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<bool>("IsImage")
                        .HasColumnType("boolean")
                        .HasColumnName("isimage")
                        .HasComment("이미지 파일 형식 여부");

                    b.Property<bool>("IsRepresentative")
                        .HasColumnType("boolean")
                        .HasColumnName("isrepresentative")
                        .HasComment("그룹 내 대표 파일(썸네일 등) 여부");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("originalname")
                        .HasComment("업로드 당시의 원본 파일명 (예: photo.png)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path")
                        .HasComment("파일이 위치한 물리적 디렉토리 상대경로");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size")
                        .HasComment("파일 크기 (단위: Bytes)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sortorder")
                        .HasComment("정렬 순서");

                    b.Property<string>("StoredName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storedname")
                        .HasComment("스토리지에 실제 저장된 난수화된 파일명 (예: uuid.png)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.HasKey("Id");

                    b.HasIndex("FileGroupId");

                    b.ToTable("filemetadatas", "scom", t =>
                        {
                            t.HasComment("개별 파일의 메타데이터 및 상세 정보를 저장하는 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("FileServer.Entities.FileMetadata", b =>
                {
                    b.HasOne("FileServer.Entities.FileGroup", "FileGroup")
                        .WithMany("Files")
                        .HasForeignKey("FileGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("FileGroup");
                });

            modelBuilder.Entity("FileServer.Entities.FileGroup", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
