// <auto-generated />
using System;
using AuthServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuthServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707115423_UpdateAllComments")]
    partial class UpdateAllComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthServer.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AvatarGroupId")
                        .HasColumnType("text")
                        .HasColumnName("avatar_group_id")
                        .HasComment("아바타 이미지 파일 그룹 식별자 (ID)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text")
                        .HasColumnName("company_id")
                        .HasComment("소속 회사 식별자 (ID)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("text")
                        .HasColumnName("department_id")
                        .HasComment("소속 부서 식별자 (ID)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password")
                        .HasComment("암호화된 비밀번호");

                    b.Property<string>("RealName")
                        .HasColumnType("text")
                        .HasColumnName("real_name")
                        .HasComment("사용자 실명 (반드시 2글자 이상 입력되어야 함)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id")
                        .HasComment("사용자 아이디 (로그인 아이디)");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name")
                        .HasComment("사용자 실명 또는 닉네임");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "DepartmentId");

                    b.ToTable("accounts", "scom", t =>
                        {
                            t.HasComment("계정 정보 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("AuthServer.Entities.AccountProfileDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_id")
                        .HasComment("연관된 사용자 계정 식별자 (ID)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content")
                        .HasComment("실제 데이터 값");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DetailType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("detail_type")
                        .HasComment("속성 유형 (Email, Phone, Fax, Photo, SNS 등)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary")
                        .HasComment("대표 여부 (여러 이메일 중 기본값 등)");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label")
                        .HasComment("라벨 (회사, 개인, 집 등)");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark")
                        .HasComment("비고 및 추가 설명");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("account_profile_details", "scom", t =>
                        {
                            t.HasComment("사용자 계정의 확장 속성 (이메일, 전화번호, 사진 등)");
                        });
                });

            modelBuilder.Entity("AuthServer.Entities.BizSelectConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("api_url")
                        .HasComment("데이터를 조회할 API 주소");

                    b.Property<string>("BizType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("biz_type")
                        .HasComment("비즈니스 유형 (예: 계정구분, 권한그룹 등 특정 콤보박스가 사용할 도메인 유형)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("http_method")
                        .HasComment("HTTP 메서드 (예: GET, POST 등, 기본값: GET)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LabelField")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_field")
                        .HasComment("화면에 표시할 텍스트에 해당하는 필드명");

                    b.Property<string>("ProcessorType")
                        .HasColumnType("text")
                        .HasColumnName("processor_type")
                        .HasComment("데이터를 파싱 및 가공할 처리기(Processor) 유형");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark")
                        .HasComment("비고 및 추가 설명");

                    b.Property<string>("ResultPath")
                        .HasColumnType("text")
                        .HasColumnName("result_path")
                        .HasComment("API 응답 JSON 내에서 실제 배열/목록이 위치하는 경로");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("ValueField")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value_field")
                        .HasComment("실제 서버로 전송할 값에 해당하는 필드명");

                    b.HasKey("Id");

                    b.ToTable("biz_select_configs", "scom", t =>
                        {
                            t.HasComment("비즈니스 콤보박스 설정 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("AuthServer.Entities.CommonCode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CodeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("code_name")
                        .HasComment("코드 명칭");

                    b.Property<string>("CodeValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code_value")
                        .HasComment("코드 값");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("group_id")
                        .HasComment("소속 공통코드 그룹 식별자 (ID)");

                    b.Property<string>("I18nKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("i18n_key")
                        .HasComment("다국어 리소스 키 (선택 사항)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("boolean")
                        .HasColumnName("is_leaf")
                        .HasComment("최하위 자식 노드 여부");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level")
                        .HasComment("계층 레벨 (1, 2, 3...)");

                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasColumnName("parent_id")
                        .HasComment("부모 코드 식별자 (ID) (다단계 구조용 자가 참조)");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark")
                        .HasComment("비고 및 추가 설명");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasComment("정렬 순서");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasComment("사용 상태 (1: 사용, 0: 미사용)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("ParentId");

                    b.ToTable("common_codes", "scom", t =>
                        {
                            t.HasComment("다단계 공통코드 엔티티 클래스 (자가 참조 구조)");
                        });
                });

            modelBuilder.Entity("AuthServer.Entities.CommonCodeGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("group_code")
                        .HasComment("그룹 코드 (예: AREA_CODE)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("group_name")
                        .HasComment("그룹 명칭");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsHierarchical")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hierarchical")
                        .HasComment("계층 구조 여부");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark")
                        .HasComment("비고 및 추가 설명");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasComment("정렬 순서");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("common_code_groups", "scom", t =>
                        {
                            t.HasComment("공통코드 그룹 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("AuthServer.Entities.Company", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address")
                        .HasComment("회사 주소");

                    b.Property<string>("AddressDetail")
                        .HasColumnType("text")
                        .HasColumnName("address_detail")
                        .HasComment("회사 상세 주소");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approval_date")
                        .HasComment("회사 승인 일자");

                    b.Property<string>("BusinessNumber")
                        .HasColumnType("text")
                        .HasColumnName("business_number")
                        .HasComment("사업자 등록 번호");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("회사 명칭");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark")
                        .HasComment("비고 및 추가 설명");

                    b.Property<string>("Representative")
                        .HasColumnType("text")
                        .HasColumnName("representative")
                        .HasComment("대표자명");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name")
                        .HasComment("회사 약칭");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasComment("정렬 순서");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasComment("회사 사용 상태 (1: 활성, 0: 비활성)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text")
                        .HasColumnName("zip_code")
                        .HasComment("우편번호");

                    b.HasKey("Id");

                    b.ToTable("companies", "scom", t =>
                        {
                            t.HasComment("회사 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("AuthServer.Entities.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_id")
                        .HasComment("소속 회사 식별자 (ID)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("부서 명칭");

                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasColumnName("parent_id")
                        .HasComment("상위 부서 식별자 (ID) (트리 구조 지원)");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark")
                        .HasComment("부서 설명 및 비고");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasComment("정렬 순서");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasComment("부서 사용 상태 (0: 비활성, 1: 활성)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("departments", "scom", t =>
                        {
                            t.HasComment("조직/부서 정보 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("AuthServer.Entities.I18nResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category")
                        .HasComment("카테고리 또는 모듈 구분 (예: common, ui, system)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key")
                        .HasComment("다국어 리소스 키 (예: common.expandAll)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("locale")
                        .HasComment("로케일 설정 (예: ko, en-US)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value")
                        .HasComment("다국어 번역 결과 텍스트 값");

                    b.HasKey("Id");

                    b.ToTable("i18n_resources", "scom", t =>
                        {
                            t.HasComment("다국어 리소스 정보를 관리하는 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("AuthServer.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("역할 명칭");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark")
                        .HasComment("역할 설명 및 비고");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasComment("역할 상태 (0: 비활성, 1: 활성)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("roles", "scom", t =>
                        {
                            t.HasComment("사용자 권한/역할 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("AuthServer.Entities.RoleAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_id")
                        .HasComment("연관된 사용자 계정 식별자 (ID)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id")
                        .HasComment("연관된 역할 식별자 (ID)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("RoleId", "AccountId")
                        .IsUnique();

                    b.ToTable("role_accounts", "scom", t =>
                        {
                            t.HasComment("역할 - 사용자 계정 매핑 엔티티 클래스 (N:M 관계 해소용 매핑 테이블)");
                        });
                });

            modelBuilder.Entity("AuthServer.Entities.RoleMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanCreate")
                        .HasColumnType("boolean")
                        .HasColumnName("can_create")
                        .HasComment("생성(등록) 권한 여부");

                    b.Property<bool>("CanCust1")
                        .HasColumnType("boolean")
                        .HasColumnName("can_cust1")
                        .HasComment("사용자 정의 권한 1 여부");

                    b.Property<bool>("CanCust2")
                        .HasColumnType("boolean")
                        .HasColumnName("can_cust2")
                        .HasComment("사용자 정의 권한 2 여부");

                    b.Property<bool>("CanCust3")
                        .HasColumnType("boolean")
                        .HasColumnName("can_cust3")
                        .HasComment("사용자 정의 권한 3 여부");

                    b.Property<bool>("CanCust4")
                        .HasColumnType("boolean")
                        .HasColumnName("can_cust4")
                        .HasComment("사용자 정의 권한 4 여부");

                    b.Property<bool>("CanCust5")
                        .HasColumnType("boolean")
                        .HasColumnName("can_cust5")
                        .HasComment("사용자 정의 권한 5 여부");

                    b.Property<bool>("CanCust6")
                        .HasColumnType("boolean")
                        .HasColumnName("can_cust6")
                        .HasComment("사용자 정의 권한 6 여부");

                    b.Property<bool>("CanCust7")
                        .HasColumnType("boolean")
                        .HasColumnName("can_cust7")
                        .HasComment("사용자 정의 권한 7 여부");

                    b.Property<bool>("CanCust8")
                        .HasColumnType("boolean")
                        .HasColumnName("can_cust8")
                        .HasComment("사용자 정의 권한 8 여부");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("can_delete")
                        .HasComment("삭제 권한 여부");

                    b.Property<bool>("CanExcel")
                        .HasColumnType("boolean")
                        .HasColumnName("can_excel")
                        .HasComment("엑셀 출력 권한 여부");

                    b.Property<bool>("CanPrint")
                        .HasColumnType("boolean")
                        .HasColumnName("can_print")
                        .HasComment("인쇄 권한 여부");

                    b.Property<bool>("CanSearch")
                        .HasColumnType("boolean")
                        .HasColumnName("can_search")
                        .HasComment("검색 권한 여부");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("boolean")
                        .HasColumnName("can_update")
                        .HasComment("수정(업데이트) 권한 여부");

                    b.Property<bool>("CanView")
                        .HasColumnType("boolean")
                        .HasColumnName("can_view")
                        .HasComment("조회(보기) 권한 여부");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MenuId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("menu_id")
                        .HasComment("연관된 시스템 메뉴 식별자 (ID)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id")
                        .HasComment("연관된 역할 식별자 (ID)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId", "MenuId")
                        .IsUnique();

                    b.ToTable("role_menus", "scom", t =>
                        {
                            t.HasComment("역할 - 메뉴 세부 권한 매핑 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("AuthServer.Entities.SystemMenu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("AffixTab")
                        .HasColumnType("boolean")
                        .HasColumnName("affix_tab")
                        .HasComment("탭 고정 여부");

                    b.Property<string>("AuthCode")
                        .HasColumnType("text")
                        .HasColumnName("auth_code")
                        .HasComment("권한 식별 코드");

                    b.Property<string>("Authority")
                        .HasColumnType("text")
                        .HasColumnName("authority")
                        .HasComment("허용 권한 목록 (콤마 구분)");

                    b.Property<string>("Badge")
                        .HasColumnType("text")
                        .HasColumnName("badge")
                        .HasComment("뱃지에 표시할 텍스트 내용");

                    b.Property<string>("BadgeType")
                        .HasColumnType("text")
                        .HasColumnName("badge_type")
                        .HasComment("뱃지 유형 (예: dot 등)");

                    b.Property<string>("Component")
                        .HasColumnType("text")
                        .HasColumnName("component")
                        .HasComment("프론트엔드 컴포넌트 파일 경로");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("DomCached")
                        .HasColumnType("boolean")
                        .HasColumnName("dom_cached")
                        .HasComment("DOM 캐싱 여부");

                    b.Property<bool>("HideInMenu")
                        .HasColumnType("boolean")
                        .HasColumnName("hide_in_menu")
                        .HasComment("메뉴 표시 숨김 여부");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon")
                        .HasComment("메뉴 아이콘 명칭 (예: AntDesign 등)");

                    b.Property<string>("IframeSrc")
                        .HasColumnType("text")
                        .HasColumnName("iframe_src")
                        .HasComment("Iframe 소스 URL (웹뷰용)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("KeepAlive")
                        .HasColumnType("boolean")
                        .HasColumnName("keep_alive")
                        .HasComment("페이지 캐싱(Keep-Alive) 적용 여부");

                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasColumnName("link")
                        .HasComment("외부 링크 URL");

                    b.Property<bool>("MenuVisibleWithForbidden")
                        .HasColumnType("boolean")
                        .HasColumnName("menu_visible_with_forbidden")
                        .HasComment("권한이 없을 때 메뉴 표시 여부");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("메뉴 이름 (다국어 키 또는 명칭)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("integer")
                        .HasColumnName("order_no")
                        .HasComment("정렬 순서");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path")
                        .HasComment("라우트 경로 (URL)");

                    b.Property<string>("Pid")
                        .HasColumnType("text")
                        .HasColumnName("pid")
                        .HasComment("부모 메뉴 식별자 (ID)");

                    b.Property<string>("Redirect")
                        .HasColumnType("text")
                        .HasColumnName("redirect")
                        .HasComment("리다이렉트할 경로 (URL)");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasComment("메뉴 사용 상태 (0: 비활성, 1: 활성)");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title")
                        .HasComment("메뉴 제목 (화면에 표시할 텍스트)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type")
                        .HasComment("메뉴 유형 (catalog, menu, button 등, 기본값: menu)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("system_menus", "scom", t =>
                        {
                            t.HasComment("시스템 메뉴 정보 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("AuthServer.Entities.Account", b =>
                {
                    b.HasOne("AuthServer.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("AuthServer.Entities.Department", "Department")
                        .WithMany("Accounts")
                        .HasForeignKey("CompanyId", "DepartmentId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AuthServer.Entities.AccountProfileDetail", b =>
                {
                    b.HasOne("AuthServer.Entities.Account", "Account")
                        .WithMany("ProfileDetails")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AuthServer.Entities.CommonCode", b =>
                {
                    b.HasOne("AuthServer.Entities.CommonCodeGroup", "Group")
                        .WithMany("Codes")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthServer.Entities.CommonCode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Group");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AuthServer.Entities.Department", b =>
                {
                    b.HasOne("AuthServer.Entities.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AuthServer.Entities.RoleAccount", b =>
                {
                    b.HasOne("AuthServer.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthServer.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AuthServer.Entities.RoleMenu", b =>
                {
                    b.HasOne("AuthServer.Entities.SystemMenu", "SystemMenu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthServer.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("SystemMenu");
                });

            modelBuilder.Entity("AuthServer.Entities.Account", b =>
                {
                    b.Navigation("ProfileDetails");
                });

            modelBuilder.Entity("AuthServer.Entities.CommonCode", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("AuthServer.Entities.CommonCodeGroup", b =>
                {
                    b.Navigation("Codes");
                });

            modelBuilder.Entity("AuthServer.Entities.Company", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("AuthServer.Entities.Department", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
