// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using funeralv2Api.Data;

#nullable disable

namespace funeralv2Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260627134316_AddOggAacToMediaSource")]
    partial class AddOggAacToMediaSource
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("funeralv2Api.Entities.Building", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("AddressDetail")
                        .HasColumnType("text")
                        .HasColumnName("address_detail");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text")
                        .HasColumnName("zip_code");

                    b.HasKey("Id");

                    b.ToTable("buildings", "smfr");
                });

            modelBuilder.Entity("funeralv2Api.Entities.Device", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("BuildingId")
                        .HasColumnType("text")
                        .HasColumnName("building_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("device_type");

                    b.Property<string>("FloorId")
                        .HasColumnType("text")
                        .HasColumnName("floor_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mac_address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("RoomId")
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("FloorId");

                    b.HasIndex("RoomId");

                    b.ToTable("devices", "smfr");
                });

            modelBuilder.Entity("funeralv2Api.Entities.DeviceAttribute", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("ContentIntervalSec")
                        .HasColumnType("integer")
                        .HasColumnName("content_interval_sec");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<string>("DisplayOrientation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("display_orientation");

                    b.Property<string>("EntranceGreeting")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entrance_greeting");

                    b.Property<int>("FloorGuideRefreshSec")
                        .HasColumnType("integer")
                        .HasColumnName("floor_guide_refresh_sec");

                    b.Property<bool>("IsActiveRoomsOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active_rooms_only");

                    b.Property<bool>("IsBuildingMapVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_building_map_visible");

                    b.Property<bool>("IsDeceasedNameVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deceased_name_visible");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<bool>("IsFamilyContactVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_family_contact_visible");

                    b.Property<bool>("IsFloorGuideEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_floor_guide_enabled");

                    b.Property<bool>("IsMediaLoop")
                        .HasColumnType("boolean")
                        .HasColumnName("is_media_loop");

                    b.Property<bool>("IsMemorialPhotoEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_memorial_photo_enabled");

                    b.Property<bool>("IsMusicEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_music_enabled");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_muted");

                    b.Property<bool>("IsNoticeVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_notice_visible");

                    b.Property<bool>("IsQrCodeVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_qr_code_visible");

                    b.Property<bool>("IsRoomAssignmentVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_room_assignment_visible");

                    b.Property<bool>("IsScreensaverEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_screensaver_enabled");

                    b.Property<bool>("IsTouchEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_touch_enabled");

                    b.Property<bool>("IsVideoEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_video_enabled");

                    b.Property<string>("MemorialPhotoEffect")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("memorial_photo_effect");

                    b.Property<int?>("MusicVolume")
                        .HasColumnType("integer")
                        .HasColumnName("music_volume");

                    b.Property<int>("NoticeScrollSpeed")
                        .HasColumnType("integer")
                        .HasColumnName("notice_scroll_speed");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<int>("ScreensaverTimeoutSec")
                        .HasColumnType("integer")
                        .HasColumnName("screensaver_timeout_sec");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("device_attributes", "smfr");
                });

            modelBuilder.Entity("funeralv2Api.Entities.DeviceConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("Brightness")
                        .HasColumnType("integer")
                        .HasColumnName("brightness");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsAutoPower")
                        .HasColumnType("boolean")
                        .HasColumnName("is_auto_power");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("PowerOffTime")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("power_off_time");

                    b.Property<string>("PowerOnTime")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("power_on_time");

                    b.Property<string>("RebootTime")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("reboot_time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.Property<int>("Volume")
                        .HasColumnType("integer")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("device_configs", "smfr");
                });

            modelBuilder.Entity("funeralv2Api.Entities.Floor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("building_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("floors", "smfr");
                });

            modelBuilder.Entity("funeralv2Api.Entities.MediaSource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AacUrl")
                        .HasColumnType("text")
                        .HasColumnName("aacurl");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("filesize");

                    b.Property<bool>("HasAac")
                        .HasColumnType("boolean")
                        .HasColumnName("hasaac");

                    b.Property<bool>("HasOgg")
                        .HasColumnType("boolean")
                        .HasColumnName("hasogg");

                    b.Property<bool>("HasThumbnail")
                        .HasColumnType("boolean")
                        .HasColumnName("hasthumbnail");

                    b.Property<bool>("HasWebm")
                        .HasColumnType("boolean")
                        .HasColumnName("haswebm");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OggUrl")
                        .HasColumnType("text")
                        .HasColumnName("oggurl");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("shortname");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sortorder");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sourcetype");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnailurl");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<string>("WebmUrl")
                        .HasColumnType("text")
                        .HasColumnName("webmurl");

                    b.HasKey("Id");

                    b.ToTable("media_sources", "smfr");
                });

            modelBuilder.Entity("funeralv2Api.Entities.Room", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("building_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("FloorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("floor_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_type");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("rooms", "smfr");
                });

            modelBuilder.Entity("funeralv2Api.Entities.Device", b =>
                {
                    b.HasOne("funeralv2Api.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId");

                    b.HasOne("funeralv2Api.Entities.Floor", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId");

                    b.HasOne("funeralv2Api.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.Navigation("Building");

                    b.Navigation("Floor");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("funeralv2Api.Entities.DeviceAttribute", b =>
                {
                    b.HasOne("funeralv2Api.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("funeralv2Api.Entities.DeviceConfig", b =>
                {
                    b.HasOne("funeralv2Api.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("funeralv2Api.Entities.Floor", b =>
                {
                    b.HasOne("funeralv2Api.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("funeralv2Api.Entities.Room", b =>
                {
                    b.HasOne("funeralv2Api.Entities.Floor", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });
#pragma warning restore 612, 618
        }
    }
}
