// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using funeralv2Api.Data;

#nullable disable

namespace funeralv2Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260710055224_AddDeviceLastSeenAt")]
    partial class AddDeviceLastSeenAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("funeralv2Api.Entities.Building", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("abbreviation")
                        .HasComment("건물 약어 (3자리 영문 대문자)");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address")
                        .HasComment("건물 주소");

                    b.Property<string>("AddressDetail")
                        .HasColumnType("text")
                        .HasColumnName("address_detail")
                        .HasComment("상세 주소");

                    b.Property<string>("BuildingPhotoGroupId")
                        .HasColumnType("text")
                        .HasColumnName("building_photo_group_id")
                        .HasComment("건물 전경 사진 파일 그룹 식별자 (ID)");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_id")
                        .HasComment("소속 회사 식별자 (ID)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("건물명");

                    b.Property<string>("ParkingPhotoGroupId")
                        .HasColumnType("text")
                        .HasColumnName("parking_photo_group_id")
                        .HasComment("주차장 안내 이미지 파일 그룹 식별자 (ID)");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark")
                        .HasComment("비고 및 추가 설명");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name")
                        .HasComment("건물 약칭");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasComment("정렬 순서");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text")
                        .HasColumnName("zip_code")
                        .HasComment("우편번호");

                    b.HasKey("Id");

                    b.ToTable("buildings", "smfr", t =>
                        {
                            t.HasComment("건물(시설물) 정보 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("funeralv2Api.Entities.Deceased", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id")
                        .HasComment("고인 식별자 (ID, GUID 또는 고유 코드)");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age")
                        .HasComment("고인 연세 (나이)");

                    b.Property<DateTime?>("BurialDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("burial_date")
                        .HasComment("발인 일시");

                    b.Property<string>("BurialPlot")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("burial_plot")
                        .HasComment("장지 위치");

                    b.Property<string>("CauseOfDeath")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cause_of_death")
                        .HasComment("사망 원인");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("최초 등록 일시");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by")
                        .HasComment("최초 등록자 식별자 (ID)");

                    b.Property<DateTime>("DeathDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("death_date")
                        .HasComment("사망 일시");

                    b.Property<string>("FamilyPhotoGroupId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("family_photo_group_id")
                        .HasComment("유족 추모용 사진 파일 그룹 식별자 (ID)");

                    b.Property<DateTime?>("FuneralDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("funeral_date")
                        .HasComment("입관/장례 일시");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender")
                        .HasComment("고인 성별 (MALE, FEMALE 등)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("삭제 여부 플래그");

                    b.Property<string>("MemorialEditedPhotoFileId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("memorial_edited_photo_file_id")
                        .HasComment("편집된 영정사진 파일 식별자 (ID)");

                    b.Property<string>("MemorialEditedPhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("memorial_edited_photo_url")
                        .HasComment("편집된(보정/배경합성 등) 영정사진 웹 URL 주소");

                    b.Property<string>("MemorialPhotoFileId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("memorial_photo_file_id")
                        .HasComment("영정사진 원본 파일 식별자 (ID)");

                    b.Property<string>("MemorialPhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("memorial_photo_url")
                        .HasComment("영정사진 웹 URL 주소");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .HasComment("고인 성명");

                    b.Property<string>("Religion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("religion")
                        .HasComment("종교");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark")
                        .HasComment("비고 및 추가 설명");

                    b.Property<string>("Ssn")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ssn")
                        .HasComment("주민등록번호");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status")
                        .HasComment("장례 진행 상태 (예: IN_HOSPITAL, DISCHARGED, COMPLETED 등, 기본값: IN_HOSPITAL)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("최종 수정 일시");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("updated_by")
                        .HasComment("최종 수정자 식별자 (ID)");

                    b.HasKey("Id");

                    b.ToTable("deceaseds", "smfr", t =>
                        {
                            t.HasComment("고인 정보 관리 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("funeralv2Api.Entities.DeceasedContractor", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id")
                        .HasComment("계약자 식별자 (ID)");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address")
                        .HasComment("계약자 주소");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contact")
                        .HasComment("계약자 연락처 (전화번호)");

                    b.Property<string>("DeceasedId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("deceased_id")
                        .HasComment("연관된 고인 식별자 (ID)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .HasComment("계약자 성명");

                    b.Property<string>("Relation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("relation")
                        .HasComment("고인과의 관계");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark")
                        .HasComment("비고 및 추가 설명");

                    b.Property<string>("SignatureFileId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("signature_file_id")
                        .HasComment("계약 서명 이미지 파일 식별자 (ID)");

                    b.HasKey("Id");

                    b.ToTable("deceased_contractors", "smfr", t =>
                        {
                            t.HasComment("고인 장례 계약자 정보 관리 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("funeralv2Api.Entities.DeceasedFacility", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id")
                        .HasComment("이용 내역 식별자 (ID)");

                    b.Property<string>("DeceasedId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("deceased_id")
                        .HasComment("연관된 고인 식별자 (ID)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time")
                        .HasComment("시설 이용 종료 일시");

                    b.Property<string>("FacilityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("facility_type")
                        .HasComment("시설 유형 (예: MORGUE, WASH_ROOM, HALL, ETC 등)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark")
                        .HasComment("비고 및 추가 설명");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time")
                        .HasComment("시설 이용 시작 일시");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("total_price")
                        .HasComment("시설 이용 총 금액");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price")
                        .HasComment("시설 시간당 이용 단가");

                    b.Property<double>("UseHours")
                        .HasColumnType("double precision")
                        .HasColumnName("use_hours")
                        .HasComment("시설 총 이용 시간");

                    b.HasKey("Id");

                    b.ToTable("deceased_facilities", "smfr", t =>
                        {
                            t.HasComment("고인별 장례 시설(안치실, 염습실, 영결식장 등) 이용 내역 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("funeralv2Api.Entities.DeceasedManager", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id")
                        .HasComment("매핑 정보 식별자 (ID)");

                    b.Property<string>("DeceasedId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("deceased_id")
                        .HasComment("연관된 고인 식별자 (ID)");

                    b.Property<string>("DirectorContact")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("director_contact")
                        .HasComment("장례지도사 연락처 (전화번호)");

                    b.Property<string>("DirectorName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("director_name")
                        .HasComment("장례지도사 성명");

                    b.Property<string>("MutualAidCompany")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mutual_aid_company")
                        .HasComment("상조회사 명칭");

                    b.Property<string>("StaffContact")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("staff_contact")
                        .HasComment("당사 담당 직원 연락처 (전화번호)");

                    b.Property<string>("StaffName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("staff_name")
                        .HasComment("당사 담당 직원 성명");

                    b.HasKey("Id");

                    b.ToTable("deceased_managers", "smfr", t =>
                        {
                            t.HasComment("고인별 장례 담당 임직원 및 지도사 매핑 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("funeralv2Api.Entities.DeceasedMourner", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id")
                        .HasComment("상주 식별자 (ID)");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address")
                        .HasComment("주소");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contact")
                        .HasComment("상주 연락처 (전화번호)");

                    b.Property<string>("DeceasedId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("deceased_id")
                        .HasComment("연관된 고인 식별자 (ID)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email")
                        .HasComment("이메일 주소");

                    b.Property<bool>("IsChief")
                        .HasColumnType("boolean")
                        .HasColumnName("is_chief")
                        .HasComment("대표 상주 여부");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("삭제 여부 플래그");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .HasComment("상주 성명");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("relation")
                        .HasComment("고인과의 관계 (예: 배우자, 자녀, 자부, 사위, 손자 등)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasComment("정렬 순서");

                    b.HasKey("Id");

                    b.ToTable("deceased_mourners", "smfr", t =>
                        {
                            t.HasComment("고인 상주 정보 관리 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("funeralv2Api.Entities.DeceasedRoom", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id")
                        .HasComment("배정 내역 식별자 (ID)");

                    b.Property<string>("DeceasedId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("deceased_id")
                        .HasComment("연관된 고인 식별자 (ID)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time")
                        .HasComment("호실 사용 종료 일시");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("삭제 여부 플래그");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("room_id")
                        .HasComment("배정된 호실(빈소) 식별자 (ID)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time")
                        .HasComment("호실 사용 시작 일시");

                    b.HasKey("Id");

                    b.ToTable("deceased_rooms", "smfr", t =>
                        {
                            t.HasComment("고인별 호실(빈소) 배정 및 사용 기간 이력 관리 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("funeralv2Api.Entities.Device", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("BuildingId")
                        .HasColumnType("text")
                        .HasColumnName("building_id")
                        .HasComment("배정된 건물 식별자 (ID)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code")
                        .HasComment("장비 코드 (고유 식별 코드)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text")
                        .HasColumnName("company_id")
                        .HasComment("소속 회사 식별자 (ID)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("device_type")
                        .HasComment("장비 유형 (예: DID, KIOSK, SIGNBOARD 등, 기본값: DID)");

                    b.Property<string>("FloorId")
                        .HasColumnType("text")
                        .HasColumnName("floor_id")
                        .HasComment("배정된 층 식별자 (ID)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address")
                        .HasComment("IP 주소");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at")
                        .HasComment("마지막 상태 확인 시간");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mac_address")
                        .HasComment("MAC 주소");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .HasComment("장비명");

                    b.Property<string>("RoomId")
                        .HasColumnType("text")
                        .HasColumnName("room_id")
                        .HasComment("배정된 호실(빈소) 식별자 (ID)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("short_name")
                        .HasComment("장비 약칭");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasComment("정렬 순서");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasComment("장비 상태 (예: ONLINE, OFFLINE, UNKNOWN 등, 기본값: UNKNOWN)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("FloorId");

                    b.HasIndex("RoomId");

                    b.ToTable("devices", "smfr", t =>
                        {
                            t.HasComment("장비(디바이스) 정보 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("funeralv2Api.Entities.DeviceAttribute", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("ContentIntervalSec")
                        .HasColumnType("integer")
                        .HasColumnName("content_interval_sec")
                        .HasComment("콘텐츠 전환 간격(초)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id")
                        .HasComment("장비 식별자 (ID)");

                    b.Property<string>("DisplayOrientation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("display_orientation")
                        .HasComment("표시 방향 (LANDSCAPE / PORTRAIT)");

                    b.Property<decimal?>("DisplayPaddingBottom")
                        .HasColumnType("numeric")
                        .HasColumnName("display_padding_bottom")
                        .HasComment("전체 화면 여백 (아래 %)");

                    b.Property<decimal?>("DisplayPaddingLeft")
                        .HasColumnType("numeric")
                        .HasColumnName("display_padding_left")
                        .HasComment("전체 화면 여백 (좌 %)");

                    b.Property<decimal?>("DisplayPaddingRight")
                        .HasColumnType("numeric")
                        .HasColumnName("display_padding_right")
                        .HasComment("전체 화면 여백 (우 %)");

                    b.Property<decimal?>("DisplayPaddingTop")
                        .HasColumnType("numeric")
                        .HasColumnName("display_padding_top")
                        .HasComment("전체 화면 여백 (위 %)");

                    b.Property<string>("EntranceGreeting")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entrance_greeting")
                        .HasComment("입구 인사말 메시지");

                    b.Property<int>("FloorGuideRefreshSec")
                        .HasColumnType("integer")
                        .HasColumnName("floor_guide_refresh_sec")
                        .HasComment("층별 안내 새로고침 간격(초)");

                    b.Property<bool>("IsActiveRoomsOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active_rooms_only")
                        .HasComment("현재 진행 중인 빈소 목록만 표시 여부");

                    b.Property<bool>("IsBuildingMapVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_building_map_visible")
                        .HasComment("건물 전체 안내도 표시 여부");

                    b.Property<bool>("IsDeceasedNameVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deceased_name_visible")
                        .HasComment("고인 이름 표시 여부");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<bool>("IsFamilyContactVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_family_contact_visible")
                        .HasComment("유족 연락처 표시 여부");

                    b.Property<bool>("IsFloorGuideEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_floor_guide_enabled")
                        .HasComment("층별 안내판 표시 활성화 여부");

                    b.Property<bool>("IsMediaLoop")
                        .HasColumnType("boolean")
                        .HasColumnName("is_media_loop")
                        .HasComment("동영상/음악 반복 재생 여부");

                    b.Property<bool>("IsMemorialPhotoEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_memorial_photo_enabled")
                        .HasComment("영정사진 표시 여부");

                    b.Property<bool>("IsMusicEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_music_enabled")
                        .HasComment("음악 재생 활성화 여부");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_muted")
                        .HasComment("음소거 여부");

                    b.Property<bool>("IsNoticeVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_notice_visible")
                        .HasComment("공지사항 표시 여부");

                    b.Property<bool>("IsQrCodeVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_qr_code_visible")
                        .HasComment("QR코드 표시 여부");

                    b.Property<bool>("IsRoomAssignmentVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_room_assignment_visible")
                        .HasComment("빈소 배정 현황 표시 여부");

                    b.Property<bool>("IsScreensaverEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_screensaver_enabled")
                        .HasComment("대기 화면 활성화 여부");

                    b.Property<bool>("IsTouchEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_touch_enabled")
                        .HasComment("터치 인터랙션 활성화 여부");

                    b.Property<bool>("IsVideoEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_video_enabled")
                        .HasComment("동영상 재생 활성화 여부");

                    b.Property<decimal?>("MemorialPaddingBottom")
                        .HasColumnType("numeric")
                        .HasColumnName("memorial_padding_bottom")
                        .HasComment("영정사진 여백 (아래 %)");

                    b.Property<decimal?>("MemorialPaddingLeft")
                        .HasColumnType("numeric")
                        .HasColumnName("memorial_padding_left")
                        .HasComment("영정사진 여백 (좌 %)");

                    b.Property<decimal?>("MemorialPaddingRight")
                        .HasColumnType("numeric")
                        .HasColumnName("memorial_padding_right")
                        .HasComment("영정사진 여백 (우 %)");

                    b.Property<decimal?>("MemorialPaddingTop")
                        .HasColumnType("numeric")
                        .HasColumnName("memorial_padding_top")
                        .HasComment("영정사진 여백 (위 %)");

                    b.Property<string>("MemorialPhotoEffect")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("memorial_photo_effect")
                        .HasComment("영정사진 표시 효과 (FADE / SLIDE / NONE)");

                    b.Property<string>("MusicId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("music_id")
                        .HasComment("재생 음악 식별자 (ID)");

                    b.Property<int?>("MusicVolume")
                        .HasColumnType("integer")
                        .HasColumnName("music_volume")
                        .HasComment("음악 재생 볼륨 (0-100, null이면 장비 기본값 사용)");

                    b.Property<int>("NoticeScrollSpeed")
                        .HasColumnType("integer")
                        .HasColumnName("notice_scroll_speed")
                        .HasComment("공지사항 스크롤 속도 (1=느림, 5=빠름)");

                    b.Property<string>("PhotoHorizontalAlignment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("photo_horizontal_alignment")
                        .HasComment("사진 가로 정렬 (LEFT / CENTER / RIGHT) - 기본값: 중앙");

                    b.Property<string>("PhotoVerticalAlignment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("photo_vertical_alignment")
                        .HasComment("사진 세로 정렬 (TOP / CENTER / BOTTOM) - 기본값: 상단");

                    b.Property<string>("PortraitOrientation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("portrait_orientation")
                        .HasComment("화면 표현 (HORIZONTAL / VERTICAL)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark")
                        .HasComment("비고 및 추가 설명");

                    b.Property<int>("ScreensaverTimeoutSec")
                        .HasColumnType("integer")
                        .HasColumnName("screensaver_timeout_sec")
                        .HasComment("대기 화면 전환 대기 시간(초)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.Property<string>("VideoId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("video_id")
                        .HasComment("재생 동영상 식별자 (ID)");

                    b.Property<string>("VideoOrientation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("video_orientation")
                        .HasComment("영상 표현 (HORIZONTAL / VERTICAL)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("device_attributes", "smfr", t =>
                        {
                            t.HasComment("장비 속성 정보 엔티티 클래스 (Device 1:N 관계)\n            장비 유형별 세부 설정 값을 key-value 형태 또는 구조화된 컬럼으로 관리합니다.");
                        });
                });

            modelBuilder.Entity("funeralv2Api.Entities.DeviceConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("Brightness")
                        .HasColumnType("integer")
                        .HasColumnName("brightness")
                        .HasComment("화면 밝기 (0-100, 기본값: 80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id")
                        .HasComment("장비 식별자 (ID)");

                    b.Property<bool>("IsAutoPower")
                        .HasColumnType("boolean")
                        .HasColumnName("is_auto_power")
                        .HasComment("자동 전원 제어 사용 여부");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("PowerOffTime")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("power_off_time")
                        .HasComment("자동 꺼짐 시각 (예: HH:mm 형식)");

                    b.Property<string>("PowerOnTime")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("power_on_time")
                        .HasComment("자동 켜짐 시각 (예: HH:mm 형식)");

                    b.Property<string>("RebootTime")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("reboot_time")
                        .HasComment("일일 자동 재시작 시각 (예: HH:mm 형식)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.Property<int>("Volume")
                        .HasColumnType("integer")
                        .HasColumnName("volume")
                        .HasComment("기기 음량 (0-100, 기본값: 50)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("device_configs", "smfr", t =>
                        {
                            t.HasComment("장비 기본 설정 엔티티 클래스 (Device 1:1 관계)\n            음량, 밝기, 자동 전원, 재시작 시각 등을 관리합니다.");
                        });
                });

            modelBuilder.Entity("funeralv2Api.Entities.DeviceRibbon", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("device_id")
                        .HasComment("장비 식별자 (ID)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(6,3)")
                        .HasColumnName("height")
                        .HasComment("화면 내 표시 높이 (%, 소수점 3자리)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("MediaSourceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("media_source_id")
                        .HasComment("장식(미디어소스) 식별자 (ID, MediaSource.SourceType = IMAGE)");

                    b.Property<decimal>("PositionLeft")
                        .HasColumnType("decimal(6,3)")
                        .HasColumnName("position_left")
                        .HasComment("화면 내 좌측 위치 (%, 소수점 3자리)");

                    b.Property<decimal>("PositionTop")
                        .HasColumnType("decimal(6,3)")
                        .HasColumnName("position_top")
                        .HasComment("화면 내 상단 위치 (%, 소수점 3자리)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark")
                        .HasComment("비고 및 추가 설명");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasComment("정렬 순서");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(6,3)")
                        .HasColumnName("width")
                        .HasComment("화면 내 표시 너비 (%, 소수점 3자리)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("MediaSourceId");

                    b.ToTable("device_ribbons", "smfr", t =>
                        {
                            t.HasComment("장비 리본 설정 엔티티 클래스\n            장비(모니터) 화면의 특정 위치에 장식(리본) 이미지를 배치하는 설정을 관리합니다.\n            위치 및 크기 값은 % 단위 (소수점 3자리)로 저장되어 다양한 해상도에서도 정확한 위치를 보장합니다.");
                        });
                });

            modelBuilder.Entity("funeralv2Api.Entities.DeviceTextOverlay", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("background_color")
                        .HasComment("배경 색상 (CSS hex 색상값 또는 'transparent')");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("device_id")
                        .HasComment("장비 식별자 (ID)");

                    b.Property<string>("FontColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("font_color")
                        .HasComment("폰트 색상 (CSS hex 색상값, 예: #FFFFFF)");

                    b.Property<decimal>("FontSize")
                        .HasColumnType("decimal(6,3)")
                        .HasColumnName("font_size")
                        .HasComment("폰트 크기 (화면 높이 대비 %, 소수점 3자리)");

                    b.Property<string>("FontWeight")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("font_weight")
                        .HasComment("폰트 굵기 (normal | bold)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(6,3)")
                        .HasColumnName("height")
                        .HasComment("화면 내 표시 높이 (%, 소수점 3자리)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<decimal>("PositionLeft")
                        .HasColumnType("decimal(6,3)")
                        .HasColumnName("position_left")
                        .HasComment("화면 내 좌측 위치 (%, 소수점 3자리)");

                    b.Property<decimal>("PositionTop")
                        .HasColumnType("decimal(6,3)")
                        .HasColumnName("position_top")
                        .HasComment("화면 내 상단 위치 (%, 소수점 3자리)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark")
                        .HasComment("비고 및 추가 설명");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasComment("정렬 순서");

                    b.Property<string>("TextAlign")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("text_align")
                        .HasComment("텍스트 정렬 방식 (left | center | right)");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text_content")
                        .HasComment("표시할 텍스트 내용");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(6,3)")
                        .HasColumnName("width")
                        .HasComment("화면 내 표시 너비 (%, 소수점 3자리)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("device_text_overlays", "smfr", t =>
                        {
                            t.HasComment("장비 텍스트 오버레이 설정 엔티티 클래스\n            장비(모니터) 화면의 특정 위치에 텍스트를 배치하는 설정을 관리합니다.\n            위치 및 크기 값은 % 단위 (소수점 3자리)로 저장되어 다양한 해상도에서도 정확한 위치를 보장합니다.");
                        });
                });

            modelBuilder.Entity("funeralv2Api.Entities.Floor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("building_id")
                        .HasComment("소속 건물 식별자 (ID)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("층 명칭 (예: 1F, B1 등)");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark")
                        .HasComment("비고 및 추가 설명");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasComment("정렬 순서");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("floors", "smfr", t =>
                        {
                            t.HasComment("건물 내 층(Floor) 정보 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("funeralv2Api.Entities.MediaSource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<Guid?>("AacFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("aacfileid")
                        .HasComment("AAC 파일의 FileMetadata 식별자");

                    b.Property<string>("AacUrl")
                        .HasColumnType("text")
                        .HasColumnName("aacurl")
                        .HasComment("음원인 경우 AAC 파일의 파일 URL 경로");

                    b.Property<string>("ConversionCommand")
                        .HasColumnType("text")
                        .HasColumnName("conversioncommand")
                        .HasComment("변환 시 사용된 FFmpeg 명령어");

                    b.Property<DateTime?>("ConversionCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("conversioncompletedat")
                        .HasComment("변환 완료 일시");

                    b.Property<DateTime?>("ConversionStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("conversionstartedat")
                        .HasComment("변환 시작 일시");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("errormessage")
                        .HasComment("미디어 변환 실패 시 발생한 에러 메시지");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("filesize")
                        .HasComment("파일 크기 (Bytes)");

                    b.Property<bool>("HasAac")
                        .HasColumnType("boolean")
                        .HasColumnName("hasaac")
                        .HasComment("AAC 파일 변환 완료 여부");

                    b.Property<bool>("HasOgg")
                        .HasColumnType("boolean")
                        .HasColumnName("hasogg")
                        .HasComment("OGG 파일 변환 완료 여부");

                    b.Property<bool>("HasThumbnail")
                        .HasColumnType("boolean")
                        .HasColumnName("hasthumbnail")
                        .HasComment("썸네일 이미지 생성 완료 여부");

                    b.Property<bool>("HasWebm")
                        .HasColumnType("boolean")
                        .HasColumnName("haswebm")
                        .HasComment("WebM 파일 변환 완료 여부");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("미디어 소스 명칭");

                    b.Property<Guid?>("OggFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("oggfileid")
                        .HasComment("OGG 파일의 FileMetadata 식별자");

                    b.Property<string>("OggUrl")
                        .HasColumnType("text")
                        .HasColumnName("oggurl")
                        .HasComment("음원인 경우 OGG 파일의 파일 URL 경로");

                    b.Property<Guid?>("OriginalFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("originalfileid")
                        .HasComment("원본 파일의 FileMetadata 식별자");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark")
                        .HasComment("설명 및 비고");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("shortname")
                        .HasComment("영상 짧은 명칭");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sortorder")
                        .HasComment("정렬 순서");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sourcetype")
                        .HasComment("미디어 유형 (VIDEO, AUDIO, IMAGE)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasComment("미디어 변환 상태 (PROCESSING, COMPLETED, FAILED)");

                    b.Property<Guid?>("ThumbnailFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("thumbnailfileid")
                        .HasComment("썸네일 이미지 파일의 FileMetadata 식별자");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnailurl")
                        .HasComment("동영상인 경우 첫 클립 썸네일 이미지의 파일 URL 경로");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url")
                        .HasComment("파일 URL 경로 (FileServer 등 보관 경로)");

                    b.Property<Guid?>("WebmFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("webmfileid")
                        .HasComment("WebM 파일의 FileMetadata 식별자");

                    b.Property<string>("WebmUrl")
                        .HasColumnType("text")
                        .HasColumnName("webmurl")
                        .HasComment("동영상인 경우 WebM 파일의 파일 URL 경로");

                    b.HasKey("Id");

                    b.ToTable("media_sources", "smfr", t =>
                        {
                            t.HasComment("미디어 소스 (동영상, 음원, 이미지 등) 리소스를 저장하는 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("funeralv2Api.Entities.Room", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("building_id")
                        .HasComment("소속 건물 식별자 (ID)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("FloorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("floor_id")
                        .HasComment("소속 층 식별자 (ID)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("호실 명칭");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark")
                        .HasComment("비고 및 추가 설명");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_type")
                        .HasComment("호실 유형 (예: 빈소, 안치실, 참관실, 영결식장 등)");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name")
                        .HasComment("호실 약칭");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order")
                        .HasComment("정렬 순서");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasComment("사용 상태 (예: ACTIVE, INACTIVE 등, 기본값: ACTIVE)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updatedby");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("rooms", "smfr", t =>
                        {
                            t.HasComment("호실(빈소, 안치실, 참관실 등) 정보 엔티티 클래스");
                        });
                });

            modelBuilder.Entity("funeralv2Api.Entities.Device", b =>
                {
                    b.HasOne("funeralv2Api.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId");

                    b.HasOne("funeralv2Api.Entities.Floor", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId");

                    b.HasOne("funeralv2Api.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.Navigation("Building");

                    b.Navigation("Floor");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("funeralv2Api.Entities.DeviceAttribute", b =>
                {
                    b.HasOne("funeralv2Api.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("funeralv2Api.Entities.DeviceConfig", b =>
                {
                    b.HasOne("funeralv2Api.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("funeralv2Api.Entities.DeviceRibbon", b =>
                {
                    b.HasOne("funeralv2Api.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("funeralv2Api.Entities.MediaSource", "MediaSource")
                        .WithMany()
                        .HasForeignKey("MediaSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("MediaSource");
                });

            modelBuilder.Entity("funeralv2Api.Entities.DeviceTextOverlay", b =>
                {
                    b.HasOne("funeralv2Api.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("funeralv2Api.Entities.Floor", b =>
                {
                    b.HasOne("funeralv2Api.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("funeralv2Api.Entities.Room", b =>
                {
                    b.HasOne("funeralv2Api.Entities.Floor", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });
#pragma warning restore 612, 618
        }
    }
}
