-- ============================================================
-- 생일 축하 메시지 표 — scom (포털 공통)
--
-- 대상 DB : jsiniportal (scom)
-- 실행    : psql -h <host> -p <port> -U funeralv2 -d jsiniportal -f docs/sql/birthday_messages.sql
--
-- 여러 번 실행해도 안전하다 (IF NOT EXISTS).
--
-- ── 왜 여기인가 ─────────────────────────────────────────────
-- 생일 기능을 A안(포털 관리)으로 정하면서(2026-08-30, 38번 문서 3절) 옮겨 왔다.
-- 보낸 이·받는 이가 모두 포털 계정(scom.accounts.user_id)이라 scom 이 맞다.
-- 원래 ghub.birthday_messages 에 있던 것을 이 표로 옮기고 그쪽은 지웠다.
-- API 는 AuthServer 의 /birthday/* 가 낸다. 컬럼 무리는 scom 공통
-- (created_*/updated_*/is_deleted — JSini.Shared BaseEntity)을 따른다.
--
-- sender_id · recipient_id 는 scom.accounts.user_id 값이다. FK 는 걸지 않는다 —
-- accounts 의 PK 가 id(GUID)라 user_id 로는 걸 수 없고(유니크 제약 없음),
-- 계정이 지워져도 받은 축하의 기록은 남기고 싶다.
-- ============================================================

CREATE TABLE IF NOT EXISTS scom.birthday_messages (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_id  varchar(100) NOT NULL,
  sender_id     varchar(100) NOT NULL,
  content       text NOT NULL,
  is_read       boolean NOT NULL DEFAULT false,
  created_at    timestamptz NOT NULL DEFAULT now(),
  created_by    text,
  updated_at    timestamptz,
  updated_by    text,
  is_deleted    boolean NOT NULL DEFAULT false
);
COMMENT ON TABLE scom.birthday_messages IS '생일 축하 메시지. sender/recipient 는 accounts.user_id';

CREATE INDEX IF NOT EXISTS ix_birthday_messages_recipient_id ON scom.birthday_messages (recipient_id);
CREATE INDEX IF NOT EXISTS ix_birthday_messages_sender_id ON scom.birthday_messages (sender_id);

-- ── 확인 ─────────────────────────────────────────────────────
SELECT count(*) AS 메시지수 FROM scom.birthday_messages;
