-- ============================================================
-- 회사 사용처 (COMPANY_USAGE_LOCATION)
-- ============================================================
--
-- DB: jsiniportal (스키마 scom)
--
-- 한 회사가 **어느 시스템에서 쓰이는지**를 공통코드로 보관한다.
-- 코드 그룹은 `COMPANY_USAGE_LOCATION`(회사 사용처)이고 이미 등록돼 있다 —
-- 장례식장관리 시스템 · 프로젝트 관리 시스템 · 헬프 데스크.
--
-- 회사 하나가 **여러 개**를 가질 수 있고, **하나도 없을 수도 있다.**
-- 그래서 회사 표에 칸을 더하지 않고 잇는 표를 둔다(scom.role_companies 와 같은 모양).
--
-- [코드의 id 가 아니라 code_value 를 담는 이유]
--
-- 화면의 공통코드 셀렉트(`DictSelect`)와 다른 시스템이 주고받는 값이 모두
-- `code_value`(예: `HELP_DESK`)다. id(GUID)를 담으면 값을 쓸 때마다 코드 표를
-- 한 번 더 들러야 하고, 코드를 지우고 다시 만들면 id 가 바뀌어 연결이 끊긴다.
-- 대신 공통코드로의 외래키는 걸지 못한다 — 코드가 사라져도 행은 남는다.
-- 남은 값은 화면에서 코드 이름을 못 찾아 값 그대로 보이므로 눈에 띈다.
--
-- 반복 실행해도 안전하다.

BEGIN;

CREATE TABLE IF NOT EXISTS scom.company_usage_locations (
    id          integer GENERATED BY DEFAULT AS IDENTITY,
    company_id  text                     NOT NULL,
    code_value  character varying(50)    NOT NULL,
    created_at  timestamp with time zone NOT NULL DEFAULT now(),
    created_by  text,
    updated_at  timestamp with time zone,
    updated_by  text,
    is_deleted  boolean                  NOT NULL DEFAULT false,
    CONSTRAINT "PK_company_usage_locations" PRIMARY KEY (id),
    CONSTRAINT "FK_company_usage_locations_companies_company_id"
        FOREIGN KEY (company_id) REFERENCES scom.companies(id) ON DELETE CASCADE
);

-- 같은 회사에 같은 코드가 두 번 들어가지 않게 한다.
CREATE UNIQUE INDEX IF NOT EXISTS "IX_company_usage_locations_company_id_code_value"
    ON scom.company_usage_locations (company_id, code_value);

CREATE INDEX IF NOT EXISTS "IX_company_usage_locations_code_value"
    ON scom.company_usage_locations (code_value);

COMMENT ON TABLE scom.company_usage_locations IS
    '회사 사용처. 공통코드 그룹 COMPANY_USAGE_LOCATION 의 code_value 를 회사마다 N 개 담는다.';

COMMIT;

-- 확인 — 고를 수 있는 코드 목록
SELECT g.group_code, c.code_value, c.code_name, c.status
FROM scom.common_codes c
JOIN scom.common_code_groups g ON g.id = c.group_id
WHERE g.group_code = 'COMPANY_USAGE_LOCATION' AND c.is_deleted = false
ORDER BY c.sort_order, c.code_value;

SELECT count(*) AS 배정건수 FROM scom.company_usage_locations WHERE is_deleted = false;
