-- ============================================================
-- LifeEnvServer(생활과환경 — 기상) 스키마
--
-- 대상 DB : ghub (jin114.co.kr:31015, 사용자 ghub, 스키마 ghub)
--           DB · 롤 · 스키마 생성은 수퍼계정으로 한 번 했다
--           (CREATE ROLE ghub LOGIN / CREATE DATABASE ghub OWNER ghub /
--            CREATE SCHEMA ghub AUTHORIZATION ghub / search_path=ghub)
-- 실행    : psql -h jin114.co.kr -p 31015 -U ghub -d ghub -f docs/sql/ghub_schema.sql
--
-- 여러 번 실행해도 안전하다 (IF NOT EXISTS).
--
-- ── 왜 이 모양인가 ───────────────────────────────────────────
-- 원본(ASIS)은 jin114.co.kr:45750 의 ghub DB 다. 그쪽은 EF 마이그레이션이
-- 만들었지만, 이 저장소 규약은 "스키마는 SQL 파일이 만든다" 라서 손으로 옮겼다.
-- 테이블 · 컬럼 이름은 ASIS 와 똑같이 유지한다 — 자료 이관이 복사만으로 끝난다.
-- (scripts/ghub-db-migration/migrate.py 가 ASIS 를 읽기 전용으로 열어 복사한다)
--
-- 감사 컬럼 무리(created_by ~ remote_machine_info, is_deleted)는 GHUB 의
-- BaseEntity 그대로다. 포털 공통(JSini.Shared.Domain)과 이름이 다르지만
-- (modified_* vs updated_*), 자료 호환을 위해 원본 이름을 지킨다.
--
-- ── 이식하지 않은 테이블 ─────────────────────────────────────
-- ASIS 의 weather_warning_details · weather_warning_codes · weather_info_reports ·
-- weather_breaking_news · weather_preliminary_warnings 는 수집 코드가 죽어 있어
-- 영구히 빈 테이블이다. 엔드포인트째 이식하지 않는다.
--
-- ── 생일은 여기 없다 (2026-08-30, A안) ──────────────────────
-- 처음에는 birthday_profiles · birthday_messages 를 여기 두었지만, 생일은
-- **포털 사용자의 속성**으로 관리하기로 했다. 정본과 API 모두 포털이다 —
-- 생일 컬럼은 scom.accounts (docs/sql/account_birthday.sql), 축하 메시지는
-- scom.birthday_messages (docs/sql/birthday_messages.sql), API 는 AuthServer.
-- 이 DB(ghub)는 기상 전용이 됐다. (docs/analysis/38-ghub-migration.md 3절)
-- ============================================================

BEGIN;

-- ── 기상: 마스터 ─────────────────────────────────────────────

-- 관측 지역
CREATE TABLE IF NOT EXISTS ghub.weather_locations (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                 varchar(100) NOT NULL,
  nx                   integer NOT NULL,
  ny                   integer NOT NULL,
  description          varchar(500),
  is_active            boolean NOT NULL DEFAULT true,
  sort_order           integer NOT NULL DEFAULT 0,
  region3              varchar(100),
  mid_term_land_code   varchar(20),
  mid_term_temp_code   text,
  warning_area_code    varchar(20),
  created_by           text NOT NULL DEFAULT '',
  created_at           timestamptz NOT NULL DEFAULT now(),
  modified_by          text,
  modified_at          timestamptz,
  action_service       text,
  menu_context         text,
  remote_addr          text,
  remote_machine_info  text,
  is_deleted           boolean NOT NULL DEFAULT false
);

-- 기준 (더위 · 강풍 · 호우 등 판정 기준)
CREATE TABLE IF NOT EXISTS ghub.weather_standards (
  id                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category              varchar(20) NOT NULL,
  name                  varchar(100) NOT NULL,
  condition_text        varchar(500) NOT NULL,
  threshold_value       double precision,
  operator              varchar(10),
  threshold_value2      double precision,
  unit                  varchar(20),
  work_status           varchar(20),
  sort_order            integer NOT NULL DEFAULT 0,
  duration              integer,
  avg_year_diff         double precision,
  prev_day_diff         double precision,
  notification_interval integer,
  use_sensible_temp     boolean NOT NULL DEFAULT false,
  created_by            text NOT NULL DEFAULT '',
  created_at            timestamptz NOT NULL DEFAULT now(),
  modified_by           text,
  modified_at           timestamptz,
  action_service        text,
  menu_context          text,
  remote_addr           text,
  remote_machine_info   text,
  is_deleted            boolean NOT NULL DEFAULT false
);

-- 기준별 대응 요령
CREATE TABLE IF NOT EXISTS ghub.weather_responses (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  weather_standard_id  integer NOT NULL REFERENCES ghub.weather_standards(id),
  action_content       text NOT NULL,
  description          text,
  sort_order           integer NOT NULL DEFAULT 0,
  created_by           text NOT NULL DEFAULT '',
  created_at           timestamptz NOT NULL DEFAULT now(),
  modified_by          text,
  modified_at          timestamptz,
  action_service       text,
  menu_context         text,
  remote_addr          text,
  remote_machine_info  text,
  is_deleted           boolean NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS ix_weather_responses_weather_standard_id
  ON ghub.weather_responses (weather_standard_id);

-- 격자좌표 (기상청 행정구역 → nx/ny 변환표, 검색 전용)
CREATE TABLE IF NOT EXISTS ghub.grid_coordinates (
  administrative_code  text PRIMARY KEY,
  category             text,
  region1              text,
  region2              text,
  region3              text,
  nx                   integer NOT NULL,
  ny                   integer NOT NULL,
  longitude_hour       integer,
  longitude_minute     integer,
  longitude_second     numeric,
  latitude_hour        integer,
  latitude_minute      integer,
  latitude_second      numeric,
  longitude_second100  numeric,
  latitude_second100   numeric,
  location_updated_at  timestamptz
);

-- 특보구역 (기상청 구역 트리 — reg_up 이 부모)
CREATE TABLE IF NOT EXISTS ghub.weather_warning_zones (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reg_id               varchar(20) NOT NULL,
  tm_st                varchar(14),
  tm_ed                varchar(14),
  reg_sp               varchar(100),
  reg_up               varchar(20),
  reg_ko               varchar(100),
  reg_name             varchar(200),
  created_by           text NOT NULL DEFAULT '',
  created_at           timestamptz NOT NULL DEFAULT now(),
  modified_by          text,
  modified_at          timestamptz,
  action_service       text,
  menu_context         text,
  remote_addr          text,
  remote_machine_info  text,
  is_deleted           boolean NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS ix_weather_warning_zones_reg_id ON ghub.weather_warning_zones (reg_id);
CREATE INDEX IF NOT EXISTS ix_weather_warning_zones_reg_up ON ghub.weather_warning_zones (reg_up);

-- ── 기상: 수집 이력 ──────────────────────────────────────────

-- 실측 (초단기 실황, 30분 주기 수집)
CREATE TABLE IF NOT EXISTS ghub.weather_infos (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location             text NOT NULL,
  weather_location_id  integer,
  observation_time     timestamptz NOT NULL,
  temperature_c        double precision NOT NULL,
  condition            text NOT NULL,
  humidity             integer,
  wind_speed           double precision,
  rainfall             double precision,
  snowfall             double precision,
  wind_direction       double precision,
  pty                  integer,
  uuu                  double precision,
  vvv                  double precision,
  sensible_temp        double precision,
  icon_url             text,
  created_by           text NOT NULL DEFAULT '',
  created_at           timestamptz NOT NULL DEFAULT now(),
  modified_by          text,
  modified_at          timestamptz,
  action_service       text,
  menu_context         text,
  remote_addr          text,
  remote_machine_info  text,
  is_deleted           boolean NOT NULL DEFAULT false
);
-- 이력 조회(/history, /forecast)가 지역+시각 범위 스캔이라 복합 인덱스를 둔다
CREATE INDEX IF NOT EXISTS ix_weather_infos_location_time
  ON ghub.weather_infos (weather_location_id, observation_time);

-- 기준 초과 이벤트
CREATE TABLE IF NOT EXISTS ghub.weather_event_records (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  weather_info_id      integer NOT NULL REFERENCES ghub.weather_infos(id),
  weather_standard_id  integer NOT NULL REFERENCES ghub.weather_standards(id),
  event_time           timestamptz NOT NULL,
  measured_value       double precision NOT NULL,
  is_notified          boolean NOT NULL DEFAULT false,
  created_by           text NOT NULL DEFAULT '',
  created_at           timestamptz NOT NULL DEFAULT now(),
  modified_by          text,
  modified_at          timestamptz,
  action_service       text,
  menu_context         text,
  remote_addr          text,
  remote_machine_info  text,
  is_deleted           boolean NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS ix_weather_event_records_weather_info_id
  ON ghub.weather_event_records (weather_info_id);
CREATE INDEX IF NOT EXISTS ix_weather_event_records_weather_standard_id
  ON ghub.weather_event_records (weather_standard_id);
CREATE INDEX IF NOT EXISTS ix_weather_event_records_event_time
  ON ghub.weather_event_records (event_time);

-- 특보
CREATE TABLE IF NOT EXISTS ghub.weather_warnings (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stn_id               integer NOT NULL,
  tm_fc                varchar(14) NOT NULL,
  tm_seq               integer NOT NULL DEFAULT 0,
  title                text NOT NULL,
  content              text NOT NULL,
  other                text,
  warning_num          text,
  announcement_time    timestamptz,
  command              text,
  collected_at         timestamptz NOT NULL,
  created_by           text NOT NULL DEFAULT '',
  created_at           timestamptz NOT NULL DEFAULT now(),
  modified_by          text,
  modified_at          timestamptz,
  action_service       text,
  menu_context         text,
  remote_addr          text,
  remote_machine_info  text,
  is_deleted           boolean NOT NULL DEFAULT false
);
-- 통보문·상태와 FK 없는 (stn_id, tm_fc, tm_seq) 값 조인이라 복합 인덱스가 필수다
CREATE INDEX IF NOT EXISTS ix_weather_warnings_key ON ghub.weather_warnings (stn_id, tm_fc, tm_seq);

-- 특보 ↔ 지역 (다대다)
CREATE TABLE IF NOT EXISTS ghub.weather_location_warnings (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  weather_warning_id   integer NOT NULL REFERENCES ghub.weather_warnings(id),
  weather_location_id  integer NOT NULL REFERENCES ghub.weather_locations(id),
  is_notified          boolean NOT NULL DEFAULT false,
  notified_at          timestamptz,
  created_by           text NOT NULL DEFAULT '',
  created_at           timestamptz NOT NULL DEFAULT now(),
  modified_by          text,
  modified_at          timestamptz,
  action_service       text,
  menu_context         text,
  remote_addr          text,
  remote_machine_info  text,
  is_deleted           boolean NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS ix_weather_location_warnings_weather_warning_id
  ON ghub.weather_location_warnings (weather_warning_id);
CREATE INDEX IF NOT EXISTS ix_weather_location_warnings_weather_location_id
  ON ghub.weather_location_warnings (weather_location_id);

-- 특보 통보문
CREATE TABLE IF NOT EXISTS ghub.weather_warning_msgs (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stn_id               integer NOT NULL,
  tm_fc                varchar(14) NOT NULL,
  tm_seq               integer NOT NULL DEFAULT 0,
  title                varchar(500) NOT NULL,
  t1 text, t2 text, t3 text, t4 text, t5 text, t6 text, t7 text,
  other                text,
  war_fc               text,
  created_by           text NOT NULL DEFAULT '',
  created_at           timestamptz NOT NULL DEFAULT now(),
  modified_by          text,
  modified_at          timestamptz,
  action_service       text,
  menu_context         text,
  remote_addr          text,
  remote_machine_info  text,
  is_deleted           boolean NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS ix_weather_warning_msgs_key
  ON ghub.weather_warning_msgs (stn_id, tm_fc, tm_seq);

-- 통보문 문장 분할
CREATE TABLE IF NOT EXISTS ghub.weather_warning_msg_sentences (
  id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  weather_warning_msg_id  integer NOT NULL REFERENCES ghub.weather_warning_msgs(id),
  field_type              varchar(10) NOT NULL,
  sequence                integer NOT NULL DEFAULT 0,
  title                   varchar(500),
  content                 text NOT NULL,
  created_by              text NOT NULL DEFAULT '',
  created_at              timestamptz NOT NULL DEFAULT now(),
  modified_by             text,
  modified_at             timestamptz,
  action_service          text,
  menu_context            text,
  remote_addr             text,
  remote_machine_info     text,
  is_deleted              boolean NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS ix_weather_warning_msg_sentences_weather_warning_msg_id
  ON ghub.weather_warning_msg_sentences (weather_warning_msg_id);

-- 특보 현황 (getPwnStatus 원본)
CREATE TABLE IF NOT EXISTS ghub.weather_warning_statuses (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stn_id               integer NOT NULL,
  tm_fc                varchar(14) NOT NULL,
  tm_ef                varchar(14) NOT NULL DEFAULT '',
  tm_seq               integer NOT NULL DEFAULT 0,
  t6 text, t7 text,
  other                text,
  content              text,
  created_by           text NOT NULL DEFAULT '',
  created_at           timestamptz NOT NULL DEFAULT now(),
  modified_by          text,
  modified_at          timestamptz,
  action_service       text,
  menu_context         text,
  remote_addr          text,
  remote_machine_info  text,
  is_deleted           boolean NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS ix_weather_warning_statuses_key
  ON ghub.weather_warning_statuses (stn_id, tm_fc, tm_seq);

-- 중기예보
CREATE TABLE IF NOT EXISTS ghub.weather_mid_term_forecasts (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  weather_location_id  integer NOT NULL REFERENCES ghub.weather_locations(id),
  base_date            varchar(12) NOT NULL,
  forecast_date        date NOT NULL,
  day_after            integer NOT NULL,
  am_sky               text NOT NULL,
  pm_sky               text NOT NULL,
  am_pop               integer NOT NULL,
  pm_pop               integer NOT NULL,
  min_temp             integer NOT NULL,
  max_temp             integer NOT NULL,
  created_at           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_weather_mid_term_forecasts_weather_location_id
  ON ghub.weather_mid_term_forecasts (weather_location_id);

-- 단기예보
CREATE TABLE IF NOT EXISTS ghub.weather_short_term_forecasts (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  weather_location_id  integer NOT NULL REFERENCES ghub.weather_locations(id),
  base_date            varchar(10) NOT NULL,
  base_time            varchar(10) NOT NULL,
  fcst_date            varchar(10) NOT NULL,
  fcst_time            varchar(10) NOT NULL,
  pop integer, pty integer, pcp text, reh integer, sno text, sky integer,
  tmp double precision, tmn double precision, tmx double precision,
  uuu double precision, vvv double precision, wav double precision,
  vec double precision, wsd double precision,
  created_at           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_weather_short_term_forecasts_weather_location_id
  ON ghub.weather_short_term_forecasts (weather_location_id);
CREATE INDEX IF NOT EXISTS ix_weather_short_term_forecasts_lookup
  ON ghub.weather_short_term_forecasts (weather_location_id, fcst_date, fcst_time);

-- 초단기예보
CREATE TABLE IF NOT EXISTS ghub.weather_ultra_srt_forecasts (
  id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  weather_location_id  integer NOT NULL REFERENCES ghub.weather_locations(id),
  base_date            varchar(10) NOT NULL,
  base_time            varchar(10) NOT NULL,
  fcst_date            varchar(10) NOT NULL,
  fcst_time            varchar(10) NOT NULL,
  t1_h double precision, rn1 text, sky integer,
  uuu double precision, vvv double precision, reh integer,
  pty integer, lgt integer, vec double precision, wsd double precision,
  created_at           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_weather_ultra_srt_forecasts_weather_location_id
  ON ghub.weather_ultra_srt_forecasts (weather_location_id);
CREATE INDEX IF NOT EXISTS ix_weather_ultra_srt_forecasts_lookup
  ON ghub.weather_ultra_srt_forecasts (weather_location_id, fcst_date, fcst_time);

COMMIT;

-- ── 확인 ─────────────────────────────────────────────────────
SELECT table_name FROM information_schema.tables
WHERE table_schema = 'ghub' ORDER BY table_name;
