<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>JSini.Shared.DTOs</AssemblyName>
    <RootNamespace>JSini.Shared.DTOs</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" />
    <ProjectReference Include="..\JSini.Shared.Domain\JSini.Shared.Domain.csproj" />
  </ItemGroup>

</Project>
