// <auto-generated />
using System;
using HelpDeskServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HelpDeskServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251017003241_InitTable2")]
    partial class InitTable2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("helpdesk")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HelpDeskServer.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionService")
                        .HasColumnType("text")
                        .HasColumnName("actionservice");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email")
                        .HasComment("이메일");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("loginid")
                        .HasComment("로그인 ID");

                    b.Property<string>("MenuContext")
                        .HasColumnType("text")
                        .HasColumnName("menucontext");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedat");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("mustchangepassword")
                        .HasComment("최초 로그인시 암호 변경 필요 여부");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash")
                        .HasComment("비밀번호 해시");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("photo")
                        .HasComment("사진 URL");

                    b.Property<string>("RemoteAddr")
                        .HasColumnType("text")
                        .HasColumnName("remoteaddr");

                    b.Property<string>("RemoteMchineInfo")
                        .HasColumnType("text")
                        .HasColumnName("remotemchineinfo");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("teamid")
                        .HasComment("팀 ID");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username")
                        .HasComment("관리자 이름");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("admin", "helpdesk", t =>
                        {
                            t.HasComment("관리자");
                        });
                });

            modelBuilder.Entity("HelpDeskServer.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionService")
                        .HasColumnType("text")
                        .HasColumnName("actionservice");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entityid")
                        .HasComment("연결된 엔티티 PK");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entitytype")
                        .HasComment("연결된 엔티티 타입");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filepath")
                        .HasComment("파일 경로");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("filesize")
                        .HasComment("파일 크기");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filetype")
                        .HasComment("파일 타입");

                    b.Property<string>("MenuContext")
                        .HasColumnType("text")
                        .HasColumnName("menucontext");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedat");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("originalfilename")
                        .HasComment("원본 파일명");

                    b.Property<string>("RemoteAddr")
                        .HasColumnType("text")
                        .HasColumnName("remoteaddr");

                    b.Property<string>("RemoteMchineInfo")
                        .HasColumnType("text")
                        .HasColumnName("remotemchineinfo");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storedfilename")
                        .HasComment("저장 파일명");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploadedat")
                        .HasComment("업로드 일시");

                    b.HasKey("Id");

                    b.ToTable("attachment", "helpdesk", t =>
                        {
                            t.HasComment("공통 첨부파일");
                        });
                });

            modelBuilder.Entity("HelpDeskServer.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionService")
                        .HasColumnType("text")
                        .HasColumnName("actionservice");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("companyid")
                        .HasComment("소속 회사 ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email")
                        .HasComment("이메일");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("loginid")
                        .HasComment("로그인 ID");

                    b.Property<string>("MenuContext")
                        .HasColumnType("text")
                        .HasColumnName("menucontext");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedat");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash")
                        .HasComment("비밀번호 해시");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("photo")
                        .HasComment("사진 URL");

                    b.Property<string>("Remake")
                        .HasColumnType("text")
                        .HasColumnName("remake")
                        .HasComment("비고");

                    b.Property<string>("RemoteAddr")
                        .HasColumnType("text")
                        .HasColumnName("remoteaddr");

                    b.Property<string>("RemoteMchineInfo")
                        .HasColumnType("text")
                        .HasColumnName("remotemchineinfo");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sex")
                        .HasComment("성별(M/F)");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasComment("계정 상태");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username")
                        .HasComment("사용자 이름");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("customer", "helpdesk", t =>
                        {
                            t.HasComment("고객");
                        });
                });

            modelBuilder.Entity("HelpDeskServer.Models.CustomerCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionService")
                        .HasColumnType("text")
                        .HasColumnName("actionservice");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("MenuContext")
                        .HasColumnType("text")
                        .HasColumnName("menucontext");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedat");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("고객사 명");

                    b.Property<string>("RemoteAddr")
                        .HasColumnType("text")
                        .HasColumnName("remoteaddr");

                    b.Property<string>("RemoteMchineInfo")
                        .HasColumnType("text")
                        .HasColumnName("remotemchineinfo");

                    b.HasKey("Id");

                    b.ToTable("customercompany", "helpdesk", t =>
                        {
                            t.HasComment("고객사");
                        });
                });

            modelBuilder.Entity("HelpDeskServer.Models.ImprovementComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionService")
                        .HasColumnType("text")
                        .HasColumnName("actionservice");

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("authorid")
                        .HasComment("작성자 ID");

                    b.Property<string>("AuthorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("authortype")
                        .HasComment("작성자 구분");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commenttext")
                        .HasComment("덧글 내용");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("MenuContext")
                        .HasColumnType("text")
                        .HasColumnName("menucontext");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedat");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("integer")
                        .HasColumnName("parentcommentid")
                        .HasComment("부모 덧글 ID");

                    b.Property<string>("RemoteAddr")
                        .HasColumnType("text")
                        .HasColumnName("remoteaddr");

                    b.Property<string>("RemoteMchineInfo")
                        .HasColumnType("text")
                        .HasColumnName("remotemchineinfo");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer")
                        .HasColumnName("requestid")
                        .HasComment("개선 요청 ID");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("RequestId");

                    b.ToTable("improvementcomment", "helpdesk", t =>
                        {
                            t.HasComment("개선 요청 덧글");
                        });
                });

            modelBuilder.Entity("HelpDeskServer.Models.ImprovementRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionService")
                        .HasColumnType("text")
                        .HasColumnName("actionservice");

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer")
                        .HasColumnName("adminid")
                        .HasComment("담당 관리자 ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customerid")
                        .HasComment("고객 ID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasComment("내용");

                    b.Property<string>("MainPhoto")
                        .HasColumnType("text")
                        .HasColumnName("mainphoto")
                        .HasComment("본문의 대표 사진");

                    b.Property<string>("MenuContext")
                        .HasColumnType("text")
                        .HasColumnName("menucontext");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedat");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<string>("RemoteAddr")
                        .HasColumnType("text")
                        .HasColumnName("remoteaddr");

                    b.Property<string>("RemoteMchineInfo")
                        .HasColumnType("text")
                        .HasColumnName("remotemchineinfo");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requestedat")
                        .HasComment("요청일시");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasComment("상태");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title")
                        .HasComment("제목");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CustomerId");

                    b.ToTable("improvementrequest", "helpdesk", t =>
                        {
                            t.HasComment("개선 요청");
                        });
                });

            modelBuilder.Entity("HelpDeskServer.Models.Notice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionService")
                        .HasColumnType("text")
                        .HasColumnName("actionservice");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content")
                        .HasComment("내용");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("MenuContext")
                        .HasColumnType("text")
                        .HasColumnName("menucontext");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedat");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<string>("RemoteAddr")
                        .HasColumnType("text")
                        .HasColumnName("remoteaddr");

                    b.Property<string>("RemoteMchineInfo")
                        .HasColumnType("text")
                        .HasColumnName("remotemchineinfo");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title")
                        .HasComment("제목");

                    b.HasKey("Id");

                    b.ToTable("notice", "helpdesk", t =>
                        {
                            t.HasComment("공지사항");
                        });
                });

            modelBuilder.Entity("HelpDeskServer.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionService")
                        .HasColumnType("text")
                        .HasColumnName("actionservice");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("MenuContext")
                        .HasColumnType("text")
                        .HasColumnName("menucontext");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedat");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("Project 명");

                    b.Property<DateTime?>("ProjectEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("projectend")
                        .HasComment("프로젝트 종료일");

                    b.Property<DateTime?>("ProjectStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("projectstart")
                        .HasComment("프로젝트 시작일");

                    b.Property<string>("RemoteAddr")
                        .HasColumnType("text")
                        .HasColumnName("remoteaddr");

                    b.Property<string>("RemoteMchineInfo")
                        .HasColumnType("text")
                        .HasColumnName("remotemchineinfo");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("teamid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("project", "helpdesk", t =>
                        {
                            t.HasComment("팀");
                        });
                });

            modelBuilder.Entity("HelpDeskServer.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionService")
                        .HasColumnType("text")
                        .HasColumnName("actionservice");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("MenuContext")
                        .HasColumnType("text")
                        .HasColumnName("menucontext");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedat");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("팀 명");

                    b.Property<string>("RemoteAddr")
                        .HasColumnType("text")
                        .HasColumnName("remoteaddr");

                    b.Property<string>("RemoteMchineInfo")
                        .HasColumnType("text")
                        .HasColumnName("remotemchineinfo");

                    b.HasKey("Id");

                    b.ToTable("team", "helpdesk", t =>
                        {
                            t.HasComment("팀");
                        });
                });

            modelBuilder.Entity("HelpDeskServer.Models.TeamCompany", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("teamid");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("companyid");

                    b.Property<int?>("CustomerCompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("customercompanyid");

                    b.HasKey("TeamId", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerCompanyId");

                    b.ToTable("teamcompanies", "helpdesk", t =>
                        {
                            t.HasComment("팀-회사 관계 (N:N)");
                        });
                });

            modelBuilder.Entity("HelpDeskServer.Models.Wbs", b =>
                {
                    b.Property<int>("WbsRid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("wbsrid")
                        .HasComment("WBS 고유 식별자 (Primary Key)");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WbsRid"));

                    b.Property<string>("ActionService")
                        .HasColumnType("text")
                        .HasColumnName("actionservice");

                    b.Property<DateTime?>("ActualEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualend")
                        .HasComment("실제 종료일");

                    b.Property<DateTime?>("ActualStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualstart")
                        .HasComment("실제 시작일");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("numeric")
                        .HasColumnName("budget")
                        .HasComment("예상 비용");

                    b.Property<int?>("BuildUserId")
                        .HasColumnType("integer")
                        .HasColumnName("builduserid");

                    b.Property<string>("Comments")
                        .HasColumnType("text")
                        .HasColumnName("comments")
                        .HasComment("작업 관련 코멘트");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost")
                        .HasComment("실제 비용");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<int?>("CustomerCompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("customercompanyid");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customerid");

                    b.Property<string>("DevCheck")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("devcheck")
                        .HasComment("개발 확인 여부");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer")
                        .HasColumnName("managerid");

                    b.Property<string>("MenuContext")
                        .HasColumnType("text")
                        .HasColumnName("menucontext");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedat");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("orderindex")
                        .HasComment("정렬 순서 인덱스");

                    b.Property<int?>("ParentWbsId")
                        .HasColumnType("integer")
                        .HasColumnName("parentwbsid");

                    b.Property<DateTime?>("PlanEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planend")
                        .HasComment("계획 종료일");

                    b.Property<DateTime?>("PlanStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planstart")
                        .HasComment("계획 시작일");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("priority")
                        .HasComment("우선순위 (High, Medium, Low 등)");

                    b.Property<decimal>("Progress")
                        .HasColumnType("numeric")
                        .HasColumnName("progress")
                        .HasComment("진행률(%)  \n            0 ~ 100 사이 값");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("projectid");

                    b.Property<string>("QcCheck")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("qccheck")
                        .HasComment("QA 확인 여부");

                    b.Property<DateTime?>("QcCheckDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("qccheckdate")
                        .HasComment("QA 확인일");

                    b.Property<int?>("QcUserId")
                        .HasColumnType("integer")
                        .HasColumnName("qcuserid");

                    b.Property<string>("RemoteAddr")
                        .HasColumnType("text")
                        .HasColumnName("remoteaddr");

                    b.Property<string>("RemoteMchineInfo")
                        .HasColumnType("text")
                        .HasColumnName("remotemchineinfo");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("integer")
                        .HasColumnName("responsibleuserid");

                    b.Property<string>("RiskLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("risklevel")
                        .HasComment("리스크 수준 (Low, Medium, High 등)");

                    b.Property<string>("ScheduleType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scheduletype")
                        .HasComment("일정 유형 (Normal, Milestone 등)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("status")
                        .HasComment("WBS 상태 (Pending, In Progress, Completed 등)");

                    b.Property<string>("WbsCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("wbscode")
                        .HasComment("WBS 코드 (예: 1.1.2)  \n            계층 구조를 표현하기 위한 식별용 코드");

                    b.Property<int?>("WbsLevel")
                        .HasColumnType("integer")
                        .HasColumnName("wbslevel")
                        .HasComment("WBS 계층(Level)");

                    b.Property<string>("WbsName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("wbsname")
                        .HasComment("WBS 이름 (작업 단위 명칭)");

                    b.Property<string>("WbsType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("wbstype")
                        .HasComment("WBS 유형 (Task, Milestone 등)");

                    b.HasKey("WbsRid");

                    b.HasIndex("BuildUserId");

                    b.HasIndex("CustomerCompanyId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ParentWbsId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("QcUserId");

                    b.HasIndex("ResponsibleUserId");

                    b.ToTable("wbs", "helpdesk", t =>
                        {
                            t.HasComment("프로젝트 WBS(Work Breakdown Structure) 엔티티\n            대규모 프로젝트에서 작업 단위, 일정, 담당자, 진행률, 리스크 등을 관리");
                        });
                });

            modelBuilder.Entity("HelpDeskServer.Models.WbsLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionService")
                        .HasColumnType("text")
                        .HasColumnName("actionservice");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("createdby");

                    b.Property<string>("MenuContext")
                        .HasColumnType("text")
                        .HasColumnName("menucontext");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modifiedat");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modifiedby");

                    b.Property<string>("RemoteAddr")
                        .HasColumnType("text")
                        .HasColumnName("remoteaddr");

                    b.Property<string>("RemoteMchineInfo")
                        .HasColumnType("text")
                        .HasColumnName("remotemchineinfo");

                    b.Property<int>("SourceWbsId")
                        .HasColumnType("integer")
                        .HasColumnName("sourcewbsid");

                    b.Property<int>("TargetWbsId")
                        .HasColumnType("integer")
                        .HasColumnName("targetwbsid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("SourceWbsId");

                    b.HasIndex("TargetWbsId");

                    b.ToTable("wbslink", "helpdesk");
                });

            modelBuilder.Entity("HelpDeskServer.Models.Admin", b =>
                {
                    b.HasOne("HelpDeskServer.Models.Team", "Team")
                        .WithMany("Admins")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HelpDeskServer.Models.Customer", b =>
                {
                    b.HasOne("HelpDeskServer.Models.CustomerCompany", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HelpDeskServer.Models.ImprovementComment", b =>
                {
                    b.HasOne("HelpDeskServer.Models.ImprovementComment", "ParentComment")
                        .WithMany("Children")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HelpDeskServer.Models.ImprovementRequest", "Request")
                        .WithMany("Comments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("HelpDeskServer.Models.ImprovementRequest", b =>
                {
                    b.HasOne("HelpDeskServer.Models.Admin", "Admin")
                        .WithMany("AssignedRequests")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HelpDeskServer.Models.Customer", "Customer")
                        .WithMany("ImprovementRequests")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("HelpDeskServer.Models.Project", b =>
                {
                    b.HasOne("HelpDeskServer.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HelpDeskServer.Models.TeamCompany", b =>
                {
                    b.HasOne("HelpDeskServer.Models.CustomerCompany", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDeskServer.Models.CustomerCompany", null)
                        .WithMany("TeamCompanies")
                        .HasForeignKey("CustomerCompanyId");

                    b.HasOne("HelpDeskServer.Models.Team", "Team")
                        .WithMany("TeamCompanies")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HelpDeskServer.Models.Wbs", b =>
                {
                    b.HasOne("HelpDeskServer.Models.Admin", "BuildUser")
                        .WithMany()
                        .HasForeignKey("BuildUserId");

                    b.HasOne("HelpDeskServer.Models.CustomerCompany", "CustomerCompany")
                        .WithMany()
                        .HasForeignKey("CustomerCompanyId");

                    b.HasOne("HelpDeskServer.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("HelpDeskServer.Models.Admin", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.HasOne("HelpDeskServer.Models.Wbs", "ParentWbs")
                        .WithMany("ChildWbs")
                        .HasForeignKey("ParentWbsId");

                    b.HasOne("HelpDeskServer.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("HelpDeskServer.Models.Admin", "QcUser")
                        .WithMany()
                        .HasForeignKey("QcUserId");

                    b.HasOne("HelpDeskServer.Models.Admin", "ResponsibleUser")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId");

                    b.Navigation("BuildUser");

                    b.Navigation("Customer");

                    b.Navigation("CustomerCompany");

                    b.Navigation("Manager");

                    b.Navigation("ParentWbs");

                    b.Navigation("Project");

                    b.Navigation("QcUser");

                    b.Navigation("ResponsibleUser");
                });

            modelBuilder.Entity("HelpDeskServer.Models.WbsLink", b =>
                {
                    b.HasOne("HelpDeskServer.Models.Wbs", "SourceWbs")
                        .WithMany()
                        .HasForeignKey("SourceWbsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDeskServer.Models.Wbs", "TargetWbs")
                        .WithMany()
                        .HasForeignKey("TargetWbsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceWbs");

                    b.Navigation("TargetWbs");
                });

            modelBuilder.Entity("HelpDeskServer.Models.Admin", b =>
                {
                    b.Navigation("AssignedRequests");
                });

            modelBuilder.Entity("HelpDeskServer.Models.Customer", b =>
                {
                    b.Navigation("ImprovementRequests");
                });

            modelBuilder.Entity("HelpDeskServer.Models.CustomerCompany", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("TeamCompanies");
                });

            modelBuilder.Entity("HelpDeskServer.Models.ImprovementComment", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("HelpDeskServer.Models.ImprovementRequest", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("HelpDeskServer.Models.Team", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("TeamCompanies");
                });

            modelBuilder.Entity("HelpDeskServer.Models.Wbs", b =>
                {
                    b.Navigation("ChildWbs");
                });
#pragma warning restore 612, 618
        }
    }
}
