<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.27" />
    <PackageReference Include="Spectre.Console" Version="0.57.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="System.Net.Http.Json" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\JSini.Shared.Domain\JSini.Shared.Domain.csproj" />
    <ProjectReference Include="..\Common\JSini.Shared.DTOs\JSini.Shared.DTOs.csproj" />
    <ProjectReference Include="..\Common\JSini.Shared.Infrastructure\JSini.Shared.Infrastructure.csproj" />
  </ItemGroup>

</Project>
