<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Funeralv2.Shared.Domain</AssemblyName>
    <RootNamespace>Funeralv2.Shared.Domain</RootNamespace>
  </PropertyGroup>

</Project>
