-- ============================================================
-- AI 대화 보관 — scom.ai_chat_sessions · ai_chat_messages (2026-10-08)
-- ============================================================
--
-- 화면: web/src/Shared/JSini.Web.Components/Layout/AiChatPanel.razor
--       (화면 /site/ai/chat 과 헤더 🤖 서랍이 같은 부품을 쓴다)
-- 서버: microservices/AIAgentServer/Services/AiChatStore.cs
--
-- **EF 마이그레이션이 아니다.** 사용량 표와 같은 자리다 —
-- deploy/sql/ai-usage-2026-10-08.sql 머리말 참고.
--
--   psql -h … -U funeralv2 -d jsiniportal -f ai-chat-2026-10-08.sql
--
-- 두 번 돌려도 안전하다.
--
-- ── 왜 서버에 담는가 — 브라우저로는 모자란다 ────────────────
--
-- 여태 대화는 **회로가 사는 동안만** 있었다. 새로고침하면 사라졌고, 옛
-- 포털도 그랬다. 「아까 물어본 것」을 다시 보려면 같은 질문을 다시 쳐야 했다.
--
-- localStorage 로도 새로고침은 넘길 수 있다. 그런데 그러면 **책상에서 쓴
-- 대화를 휴대폰에서 못 본다.** 이 포털은 같은 사람이 기기를 옮겨 다니며
-- 쓰는 물건이고, AI쳇은 헤더 서랍으로 어디서나 열린다 — 기기에 묶이면
-- 「분명히 물어봤는데 없다」가 난다. 그리고 브라우저 저장소를 비우는 일은
-- 사람들이 문제 해결하려고 흔히 하는 짓이라, 거기 둔 기록은 언젠가 사라진다.
--
-- ── 주제별로 나눈다 ─────────────────────────────────────────
--
-- 한 줄기로 길게 이어 두면 다음 턴마다 **그 전체가 문맥으로 다시 올라간다** —
-- 토큰이 눈덩이가 되고(사용량 화면에서 그대로 보인다) 상관없는 옛 얘기가
-- 답을 흐린다. 주제가 바뀌면 새 대화를 여는 것이 맞다.
--
-- 제목은 **첫 질문에서 따온다.** 사람에게 먼저 제목을 묻는 화면은 아무도
-- 안 쓴다 — 물어보려고 연 창에서 제목부터 지으라고 하면 그 자리에서 막힌다.
-- 마음에 안 들면 그때 고친다.
--
-- ── 지운 것은 바로 지운다 ───────────────────────────────────
--
-- 자기 대화를 자기가 지우는 일이다. 표시만 해 두면(soft delete) 「지웠는데
-- 어딘가 남아 있다」가 되는데, 이 자료는 **본인이 물어본 말**이라 그 기대를
-- 어기면 안 된다. 줄은 세션을 따라 함께 지워진다(ON DELETE CASCADE).
-- ============================================================

-- ── 대화 한 줄기 ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS scom.ai_chat_sessions (
    id              text          PRIMARY KEY,

    -- 누구의 것인가. scom.accounts.user_id(로그인 아이디)다.
    -- **남의 것은 열 수도 지울 수도 없다** — 서버가 이 칸으로 가른다.
    user_id         text          NOT NULL,

    -- 사람에게 보여 줄 주제. **비어 있을 수 있다** — 만들자마자 아직 아무
    -- 말도 안 한 대화다. 첫 질문이 들어오면 거기서 따온다.
    title           text,

    created_at      timestamptz   NOT NULL DEFAULT now(),

    -- 마지막으로 말이 오간 때. **목록의 차례가 이 값이다** — 여는 것만으로는
    -- 바뀌지 않는다(읽었다고 차례가 바뀌면 목록이 손댈 때마다 뒤집힌다).
    updated_at      timestamptz   NOT NULL DEFAULT now()
);

-- 내 목록을 최근 순으로 연다. 이 화면의 거의 모든 조회가 이 차례다.
CREATE INDEX IF NOT EXISTS ix_ai_chat_sessions_user
    ON scom.ai_chat_sessions (user_id, updated_at DESC);

-- ── 대화 속 한 마디 ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS scom.ai_chat_messages (
    id              bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    session_id      text          NOT NULL
        REFERENCES scom.ai_chat_sessions (id) ON DELETE CASCADE,

    -- user · assistant. **system 은 담지 않는다** — 그 줄은 서버가 매번
    -- 붙이는 지시문이라 사람의 대화가 아니고, 담아 두면 지시문을 고쳤을 때
    -- 옛 대화만 옛 지시문을 들고 다닌다.
    role            text          NOT NULL,

    content         text          NOT NULL,

    -- 차례. **시각으로 세우지 않는다** — 질문과 답이 같은 초에 들어오면
    -- 둘의 앞뒤가 뒤집힌다.
    seq             integer       NOT NULL,

    created_at      timestamptz   NOT NULL DEFAULT now()
);

-- 한 대화를 열 때 차례대로 읽는다.
CREATE UNIQUE INDEX IF NOT EXISTS ux_ai_chat_messages_seq
    ON scom.ai_chat_messages (session_id, seq);

COMMENT ON TABLE  scom.ai_chat_sessions IS 'AI쳇 대화 한 줄기(주제 하나)';
COMMENT ON COLUMN scom.ai_chat_sessions.user_id IS '주인. 남의 것은 열 수도 지울 수도 없다';
COMMENT ON COLUMN scom.ai_chat_sessions.title IS '첫 질문에서 따온 주제. 아직 말이 없으면 NULL';
COMMENT ON COLUMN scom.ai_chat_sessions.updated_at IS '마지막으로 말이 오간 때. 목록 차례의 기준';
COMMENT ON TABLE  scom.ai_chat_messages IS '대화 속 한 마디. system 지시문은 담지 않는다';
COMMENT ON COLUMN scom.ai_chat_messages.seq IS '차례. 같은 초에 들어온 질문과 답을 가른다';
