-- ============================================================
-- AI 호출 한 건 — scom.ai_usage_logs (2026-10-08)
-- ============================================================
--
-- 화면: web/src/Apps/JSini.Web.Admin/Components/Pages/AiUsageList.razor
-- 쓰는 쪽: microservices/AIAgentServer/Services/AiUsageLog.cs
--
-- **EF 마이그레이션이 아니다.** AIAgentServer 에는 Migrations 폴더가 없고
-- scom 의 이력은 AuthServer · FileServer 가 함께 쓴다. NotificationServer 가
-- 자기 표를 SQL 로 만드는 것과 같은 자리다. 운영 반영은 손으로 한 번 돌린다.
--
--   psql -h … -U funeralv2 -d jsiniportal -f ai-usage-2026-10-08.sql
--
-- 두 번 돌려도 안전하다.
--
-- ── 왜 표가 필요한가 — LLM 서버는 사람을 모른다 ──────────────
--
-- 「누가 얼마나 썼나」를 LLM 쪽에 물어볼 수가 없다. llama.cpp 는 토큰 수를
-- 응답에 실어 주지만(usage · timings) **그것은 요청 한 건의 값**이고, 포털의
-- 모든 요청은 API 키 하나로 들어가므로 서버 쪽에는 전부 같은 손님이다.
-- 사람을 아는 자리는 **AIAgentServer 하나뿐**이다 — 게이트웨이가 붙여 주는
-- X-User-Id 가 거기까지만 온다. 그래서 그 자리에서 줍어 여기 적는다.
--
-- ── 집계가 아니라 **한 줄씩** 쌓는다 ────────────────────────
--
-- 사람×날짜로 미리 더해 두면 「어제 오후에 무엇을 물었길래 토큰이 튀었나」를
-- 되짚을 수 없다. 이 표가 답해야 하는 물음이 「누가 많이 쓰나」 하나가
-- 아니라 「왜 많나」까지라서, 줄을 남기고 더하는 일은 조회가 한다.
--
-- 한 줄은 **대화 한 번이 아니라 호출 한 번**이다. 사람이 한 줄 물을 때마다
-- 그 앞의 대화 전체가 문맥으로 다시 올라가므로, prompt_tokens 는 대화가
-- 길어질수록 커진다 — 그것이 이 표가 보여 주려는 값이기도 하다.
--
-- ── 모르는 것과 0 을 가른다 ─────────────────────────────────
--
-- 토큰 칸은 전부 NULL 을 허용한다. 공급자가 usage 를 안 주는 경우가 있고
-- (Anthropic SDK 경로 · usage 를 못 읽은 스트림), 그때 0 으로 적으면
-- 「안 썼다」로 읽혀 합계가 조용히 틀린다. 호출 건수는 언제나 맞고
-- 토큰은 **준 것만** 더한다.
-- ============================================================

CREATE TABLE IF NOT EXISTS scom.ai_usage_logs (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 언제. **UTC 다**(docs/utc-time.md). 한국 시각은 보여 주기 직전에 만든다.
    occurred_at         timestamptz   NOT NULL DEFAULT now(),

    -- 누가. scom.accounts.user_id(로그인 아이디)다.
    --
    -- **NULL 일 수 있다.** 게이트웨이를 거치지 않은 내부 호출(헬스체크의
    -- 정밀 확인 따위)에는 사람이 없다. 그것을 빈 글자로 적으면 조회에서
    -- 「이름 없는 사용자 한 명」으로 뭉쳐 사람 수가 틀린다.
    user_id             text,

    -- 무엇이 불렀나 — chat · chat-stream · suggest-code · suggest-i18n · health-deep.
    -- 「AI쳇 사용량」을 보려면 앞의 둘만 세면 된다. 한 표에 담되 갈라 볼 수
    -- 있게 두는 것은, 토큰이 튀었을 때 그것이 대화인지 자동완성인지가
    -- 먼저 나와야 하기 때문이다.
    feature             text          NOT NULL,

    -- 어느 AI 가 답했나. **고른 것이 아니라 실제로 답한 것**이다 —
    -- 자동 전환·모델 바꿔치기가 있어 둘이 다를 수 있다.
    provider_key        text          NOT NULL,
    model               text,

    -- 공급자가 준 토큰 수. 안 주면 NULL (위 머리말).
    prompt_tokens       integer,
    completion_tokens   integer,
    total_tokens        integer,

    -- 호출에 걸린 시간. 스트리밍은 **마지막 조각까지**의 시간이다.
    latency_ms          integer,

    -- 답을 받았나. 거짓이면 토큰 칸이 비고 fail_reason 에 까닭이 있다.
    -- 실패도 남기는 것은 「많이 쓰는데 자꾸 실패한다」가 한도·장비 문제의
    -- 첫 신호이기 때문이다.
    ok                  boolean       NOT NULL DEFAULT true,
    fail_reason         text
);

-- 기간으로 훑는다. 화면의 기본 조회가 「최근 30일」이라 이 차례가 바로 쓰인다.
CREATE INDEX IF NOT EXISTS ix_ai_usage_logs_occurred
    ON scom.ai_usage_logs (occurred_at DESC);

-- 한 사람을 파고들 때. 사용자별 집계에서 줄을 눌러 들어가는 길이다.
CREATE INDEX IF NOT EXISTS ix_ai_usage_logs_user
    ON scom.ai_usage_logs (user_id, occurred_at DESC);

COMMENT ON TABLE  scom.ai_usage_logs IS 'AI 호출 한 건. 사람별 LLM 사용량의 정본';
COMMENT ON COLUMN scom.ai_usage_logs.user_id IS '로그인 아이디(scom.accounts.user_id). 내부 호출이면 NULL';
COMMENT ON COLUMN scom.ai_usage_logs.feature IS 'chat · chat-stream · suggest-code · suggest-i18n · health-deep';
COMMENT ON COLUMN scom.ai_usage_logs.provider_key IS '실제로 답한 공급자(자동 전환 뒤의 값)';
COMMENT ON COLUMN scom.ai_usage_logs.total_tokens IS '공급자가 준 값. 안 주면 NULL — 0 과 다르다';
