-- ============================================================
-- 메뉴 열람 한 건 — scom.menu_usage_logs (2026-10-09)
-- ============================================================
--
-- 화면: web/src/Apps/JSini.Web.Admin/Components/Pages/MenuUsageList.razor
-- 쓰는 쪽: web/src/Shared/JSini.Web.Components/Layout/MenuUsageRecorder.cs
--          → POST /api/auth/menu-usage → AuthServer 의 MenuUsageService
--
-- **이것은 EF 마이그레이션 `20261009141510_AddMenuUsageLogs` 를 그대로 뽑은
-- 것이다.** AuthServer 는 기동할 때 마이그레이션을 돌리지 않으므로(그 일을
-- 하는 곳은 FileServer 뿐이다) 운영 반영은 이 파일을 손으로 한 번 돌린다.
-- 맨 끝에서 scom."__EFMigrationsHistory" 에 줄을 넣는 것이 그래서 꼭 필요하다 —
-- 안 넣으면 다음에 누가 `dotnet ef database update` 를 돌릴 때 같은 표를
-- 한 번 더 만들려다 멈춘다.
--
--   psql -h … -U funeralv2 -d jsiniportal -f menu-usage-2026-10-09.sql
--
-- 두 번 돌려도 안전하다(각 단계가 이력을 먼저 본다).
--
-- ── 왜 표가 필요한가 ────────────────────────────────────────
--
-- 「누가 어떤 화면을 언제 보았나」를 어디에도 묻을 수 없었다. 로그인 기록
-- (scom.account_login_logs)은 들어온 것까지만 알고, 컨테이너 로그는 10MB 3개로
-- 돌려 쓰므로 바쁜 날에는 그날 안에 밀려 나간다. 게다가 포털은 한 회로 안에서
-- 라우팅만 바뀌므로 화면을 옮겨도 **서버에 HTTP 요청이 남지 않는다** —
-- 나중에 접근 로그를 뒤져도 거기에는 아무것도 없다.
--
-- 그래서 셸이 화면을 열 때(MainLayout.Track) 한 줄씩 밀어 넣는다.
--
-- ── 집계가 아니라 **한 줄씩** 쌓는다 ────────────────────────
--
-- 사람×화면으로 미리 더해 두면 「그날 오후를 어떻게 보냈나」를 되짚을 수
-- 없다. 이 표가 답해야 하는 물음이 「누가 많이 쓰나」 하나가 아니라
-- **일자별 타임라인**까지라서, 줄을 남기고 더하는 일은 조회가 한다
-- (scom.ai_usage_logs 가 같은 판단을 한 자리와 같다).
--
-- ── 열쇠를 셋이나 적는 까닭 ─────────────────────────────────
--
-- menu_id 는 메뉴가 지워지면 가리킬 곳이 없어지고, route_key 는 아직 안 채운
-- 메뉴가 있고(이행 중 — docs/menu-route-key-backfill.sql), menu_path 는
-- 권한표의 열쇠라 안 바뀌지만 Vue 시절 값이 섞여 있다. 셋 중 하나만 들고
-- 있으면 그 하나가 빈 줄이 조회에서 사라지므로 받은 것을 다 적어 둔다.
--
-- **menu_id 에 외래키를 걸지 않는다.** 메뉴를 지우면 그 화면을 본 기록까지
-- 함께 사라지는데, 지난 일을 적어 둔 표에서 그것은 자료 손실이다.
-- menu_title 을 함께 적어 두는 것도 같은 까닭이다 — 메뉴가 없어져도
-- 「그때 그 사람이 본 글자」는 남아야 한다.
-- ============================================================

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM scom."__EFMigrationsHistory" WHERE "MigrationId" = '20261009141510_AddMenuUsageLogs') THEN
    CREATE TABLE scom.menu_usage_logs (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        occurred_at timestamp with time zone NOT NULL,
        user_id character varying(128) NOT NULL,
        menu_id character varying(64),
        route_key character varying(128),
        menu_path character varying(512) NOT NULL,
        menu_title character varying(256),
        href character varying(512),
        from_path character varying(512),
        CONSTRAINT "PK_menu_usage_logs" PRIMARY KEY (id)
    );
    COMMENT ON TABLE scom.menu_usage_logs IS '메뉴 열람 한 건 — 누가 어떤 화면을 언제 보았나.';
    COMMENT ON COLUMN scom.menu_usage_logs.id IS '줄 번호';
    COMMENT ON COLUMN scom.menu_usage_logs.occurred_at IS '본 때 (UTC)';
    COMMENT ON COLUMN scom.menu_usage_logs.user_id IS '본 사람의 로그인 아이디 (scom.accounts.user_id)';
    COMMENT ON COLUMN scom.menu_usage_logs.menu_id IS '본 메뉴의 식별자 (scom.system_menus.id). 못 찾으면 비어 있다';
    COMMENT ON COLUMN scom.menu_usage_logs.route_key IS '화면이 선언한 열쇠 (예: admin.status.menu-usage)';
    COMMENT ON COLUMN scom.menu_usage_logs.menu_path IS '메뉴 경로. 권한표와 같은 열쇠이고 조회는 이것으로 묶는다';
    COMMENT ON COLUMN scom.menu_usage_logs.menu_title IS '그때 화면에 적혀 있던 메뉴 제목';
    COMMENT ON COLUMN scom.menu_usage_logs.href IS '실제로 열린 주소. 메뉴 경로와 다를 수 있다';
    COMMENT ON COLUMN scom.menu_usage_logs.from_path IS '직전에 보던 화면의 메뉴 경로. 첫 화면이면 비어 있다';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM scom."__EFMigrationsHistory" WHERE "MigrationId" = '20261009141510_AddMenuUsageLogs') THEN
    CREATE INDEX "IX_menu_usage_logs_menu_path" ON scom.menu_usage_logs (menu_path);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM scom."__EFMigrationsHistory" WHERE "MigrationId" = '20261009141510_AddMenuUsageLogs') THEN
    CREATE INDEX "IX_menu_usage_logs_occurred_at" ON scom.menu_usage_logs (occurred_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM scom."__EFMigrationsHistory" WHERE "MigrationId" = '20261009141510_AddMenuUsageLogs') THEN
    CREATE INDEX "IX_menu_usage_logs_user_id_occurred_at" ON scom.menu_usage_logs (user_id, occurred_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM scom."__EFMigrationsHistory" WHERE "MigrationId" = '20261009141510_AddMenuUsageLogs') THEN
    INSERT INTO scom."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261009141510_AddMenuUsageLogs', '10.0.11');
    END IF;
END $EF$;
COMMIT;

