-- ============================================================
-- AI 모델 한도 스냅샷 — projmng.ai_usage_snapshot (2026-09-20)
-- ============================================================
--
-- 설계: docs/ai-task-runner.md
-- 화면: web/src/Apps/JSini.Web.ProjMng/Components/Pages/AiDashboard.razor
--
-- **EF 마이그레이션이 아니다.** ProjMngServer 는 Dapper + Npgsql 이라
-- 스키마를 SQL 파일이 만든다. 운영 반영은 손으로 한 번 돌린다.
--
--   psql -h … -U projmng -d projmng -f projmng-ai-usage-2026-09-20.sql
--
-- 두 번 돌려도 안전하다.
--
-- ── 왜 표가 필요한가 ────────────────────────────────────────
--
-- 「지금 얼마나 남았나」는 **CLI 만 안다**. `claude` 의 `/usage` 가 그것을
-- 말해 주는데, 그 CLI 는 실행기 장비에만 있고 웹 서버에서 부를 수 없다
-- (부를 수 있어도 부르면 안 된다 — 셸을 여는 권한을 웹 요청 받는 프로세스에
-- 두지 않는 것이 이 기능 전체의 전제다).
--
-- 그래서 **실행기가 주기적으로 읽어 올려 둔다.** 화면은 그 마지막 값을 본다.
-- AIAgentServer 가 응답 헤더에서 한도를 줍는 것과 같은 생각이다
-- (`AiUsageTracker` — 물어보지 않고 지나가는 것을 줍는다).
--
-- ── 장비 × 종류로 **한 줄만** 둔다 ──────────────────────────
--
-- 이력을 쌓지 않는다. 이 값이 답하는 질문은 「지금 남았나」 하나이고,
-- 15분에 한 번 도는 수집을 이력으로 쌓으면 한 달에 3천 줄이 앉는다.
-- 추세가 필요해지면 그때 별도 표로 판다 — 이 표를 늘리지 않는다.
CREATE TABLE IF NOT EXISTS projmng.ai_usage_snapshot (
    usage_key       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 어느 장비에서 읽었나. 같은 계정이라도 장비마다 다를 수 있다.
    runner_nm       varchar(100)  NOT NULL,
    -- 어느 CLI 의 한도인가 — claude · antigravity · copilot
    runner_kind     varchar(20)   NOT NULL,

    -- **읽기에 성공했는가.** 거짓이면 아래 숫자가 전부 비어 있고
    -- error_text 에 이유가 있다. 실패를 안 적으면 화면이 「오래된 값」과
    -- 「읽지 못하는 중」을 구별할 수 없다.
    ok              boolean       NOT NULL DEFAULT true,

    -- 세션 한도(claude 는 5시간 창). 퍼센트는 **쓴 비율**이다.
    session_pct     numeric(5,2),
    session_reset_at timestamp,

    -- 주간 한도.
    week_pct        numeric(5,2),
    week_reset_at   timestamp,

    -- 주간 한도 중 특정 모델만 따로 세는 칸(claude 의 Opus 주간 한도).
    -- 없는 CLI 는 비운다.
    week_opus_pct   numeric(5,2),
    week_opus_reset_at timestamp,

    -- 토큰으로 주는 CLI 를 위한 칸. 퍼센트만 주는 CLI 는 비운다.
    limit_tokens    bigint,
    remaining_tokens bigint,

    -- 요금제 이름(Max · Pro …). CLI 가 말해 주면 적는다.
    plan_nm         varchar(50),

    -- **가려낸 숫자가 전부가 아니다.** CLI 의 출력 형식은 자주 바뀌고,
    -- 못 알아본 줄이 있을 때 사람이 원문을 봐야 무엇이 바뀌었는지 안다.
    raw_text        text,
    error_text      varchar(1000),

    -- **언제 기준의 값인가.** 이것이 없으면 숫자를 믿을 수 없다.
    observed_at     timestamp     NOT NULL DEFAULT now(),
    cre_dt          timestamp     DEFAULT now(),
    mod_dt          timestamp
);

-- 덮어쓰기(upsert)가 이 제약을 탄다.
CREATE UNIQUE INDEX IF NOT EXISTS ux_ai_usage_snapshot
    ON projmng.ai_usage_snapshot (runner_nm, runner_kind);

COMMENT ON TABLE projmng.ai_usage_snapshot IS
    'AI CLI 의 /usage 를 실행기가 읽어 올려 둔 마지막 값. 장비 × 종류로 한 줄.';

-- ── 대시보드가 타는 길 ──────────────────────────────────────
--
-- 집계는 실행 이력을 기간으로 훑는다. 지금 있는 인덱스는
-- `(task_key, seq DESC)` 뿐이라 **기간 조회가 전수 조사**가 된다.
-- 건수가 적은 지금은 티가 안 나지만, 이 화면은 열 때마다 여덟 번 훑는다.
CREATE INDEX IF NOT EXISTS ix_ai_task_run_started
    ON projmng.ai_task_run (started_at);

-- 「지시자별」 집계와 최근 목록이 탄다.
CREATE INDEX IF NOT EXISTS ix_ai_task_cre
    ON projmng.ai_task (cre_id, cre_dt) WHERE is_deleted = false;

-- ── 확인 ─────────────────────────────────────────────────────
-- SELECT runner_nm, runner_kind, ok, session_pct, week_pct, observed_at
--   FROM projmng.ai_usage_snapshot ORDER BY runner_nm, runner_kind;
