-- ============================================================
-- AI 작업 지시 — 표 다섯 (projmng 스키마)
-- ============================================================
--
-- 설계: docs/ai-task-runner.md
--
-- **EF 마이그레이션이 아니다.** ProjMngServer 는 Dapper + Npgsql 이라
-- 스키마를 SQL 파일이 만든다 (그 문서 4.6). 운영 반영은 손으로 한 번 돌린다.
--
-- 두 번 돌려도 안전하다 — 운영 반영을 손으로 하는 구조라 「돌렸던가?」가
-- 반드시 생긴다. 전부 IF NOT EXISTS 다.
--
--   psql -h … -U projmng -d projmng -f projmng-ai-tasks-2026-09-17.sql
--
-- 시각은 timestamp(without time zone) 다 — 이 스키마의 다른 표(home_todo 등)와
-- 같은 모양으로 맞춘다. 섞으면 조회에서 조용히 어긋난다.

-- ── 작업 대상 ────────────────────────────────────────────────
--
-- **사람이 경로를 타이핑하지 않게 하려고 있는 표다**(문서 9.5).
-- 등록은 관리자가, 선택은 작성자가 한다. 화면은 이 목록에서 고르기만 한다.
CREATE TABLE IF NOT EXISTS projmng.ai_target (
    target_key      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_nm       varchar(100)  NOT NULL,
    -- repo(git 저장소) · folder(그냥 폴더)
    target_kind     varchar(10)   NOT NULL DEFAULT 'repo',
    -- 운영 서버의 절대 경로. 등록할 때 검사한다(문서 9.5)
    target_path     varchar(500)  NOT NULL,
    repo_url        varchar(300),
    default_ref     varchar(100)  DEFAULT 'main',
    -- 비공개 저장소일 때 쓸 읽기 전용 키의 **이름**. 키 자체는 DB 에 넣지 않는다
    credential_ref  varchar(100),
    -- worktree(repo) · copy(폴더 복사본) · inplace(원본 직접)
    isolation_mode  varchar(10)   NOT NULL DEFAULT 'worktree',
    -- copy 일 때 복사 상한. 넘으면 실행을 거절한다
    max_size_mb     int,
    -- 이 대상에 쓸 수 있는 CLI. 쉼표로 잇는다 (claude,antigravity)
    runner_kinds    varchar(100)  NOT NULL DEFAULT 'claude',
    -- push 를 허용하는 대상인가. 켜면 그 작업이 곧 운영 배포가 된다(문서 9.3)
    allow_push      boolean       NOT NULL DEFAULT false,
    push_ref        varchar(100)  DEFAULT 'main',
    -- push 전에 돌릴 검사 — build · test · none
    gate_mode       varchar(10)   NOT NULL DEFAULT 'build',
    is_enabled      boolean       NOT NULL DEFAULT true,
    -- **대상별 동시 1건 잠금.** 비어 있어야 새로 집는다.
    -- 폴더 대상은 worktree 가 없어 둘이 겹치면 서로의 파일을 덮는다.
    running_run_key bigint,
    comments        varchar(500),
    is_deleted      boolean       NOT NULL DEFAULT false,
    cre_id          varchar(50),
    cre_dt          timestamp     DEFAULT now(),
    mod_id          varchar(50),
    mod_dt          timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ai_target_nm
    ON projmng.ai_target (target_nm) WHERE is_deleted = false;

-- ── 작업 한 건 (사람이 쓰는 글) ──────────────────────────────
CREATE TABLE IF NOT EXISTS projmng.ai_task (
    task_key        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           varchar(200)  NOT NULL,
    contents        text          NOT NULL,
    content_format  varchar(20)   NOT NULL DEFAULT 'markdown',

    target_key      bigint        REFERENCES projmng.ai_target (target_key),
    -- 저장소 대상일 때 기준 브랜치. 비우면 대상의 기본값
    target_ref      varchar(100),
    runner_kind     varchar(20)   NOT NULL DEFAULT 'claude',

    -- **작업요청여부** — 사람의 의사. none · requested · cancel_requested
    request_flag    varchar(20)   NOT NULL DEFAULT 'none',
    -- **작업상태** — 기계의 현재 위치.
    -- idle · queued · preparing · running · succeeded · failed
    -- · timeout · canceled · interrupted
    task_status     varchar(20)   NOT NULL DEFAULT 'idle',

    priority        int           NOT NULL DEFAULT 0,
    timeout_minutes int           NOT NULL DEFAULT 30,
    attempt_count   int           NOT NULL DEFAULT 0,
    -- 기본 1 — 파일을 고치는 작업이라 자동 재시도가 안전하지 않다(문서 6.11)
    attempt_max     int           NOT NULL DEFAULT 1,

    -- push 까지 할 것인가. 대상이 allow_push 일 때만 켤 수 있다
    auto_push       boolean       NOT NULL DEFAULT false,

    -- 끝나면 메일로 받기(문서 8-2)
    notify_email    boolean       NOT NULL DEFAULT false,
    notify_to       varchar(200),
    -- always · on_success · on_failure
    notify_when     varchar(20)   NOT NULL DEFAULT 'always',
    notify_error    varchar(500),

    requested_at    timestamp,
    started_at      timestamp,
    finished_at     timestamp,
    duration_ms     bigint,

    last_run_key    bigint,
    last_exit_code  int,
    last_error      varchar(1000),

    -- 비어 있지 않으면 **운영 배포가 일어났다는 뜻**이다
    pushed_commit   varchar(64),
    -- push 직전의 운영 TAG. 되돌릴 때 필요한 값이다(문서 9.3)
    previous_tag    varchar(64),

    -- 동시 편집 방지(낙관적 잠금)
    row_version     int           NOT NULL DEFAULT 1,
    is_deleted      boolean       NOT NULL DEFAULT false,
    cre_id          varchar(50),
    cre_dt          timestamp     DEFAULT now(),
    mod_id          varchar(50),
    mod_dt          timestamp
);

-- 집어가는 조회가 타는 길이다 — 요청된 것 중 아직 안 집은 것.
-- FOR UPDATE SKIP LOCKED 가 이 인덱스를 쓴다(문서 6.5).
CREATE INDEX IF NOT EXISTS ix_ai_task_pick
    ON projmng.ai_task (request_flag, task_status, priority DESC, requested_at)
    WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS ix_ai_task_target
    ON projmng.ai_task (target_key) WHERE is_deleted = false;

-- ── 실행 한 번 ───────────────────────────────────────────────
--
-- 같은 글을 여러 번 돌린다. 한 줄에 상태를 다 담으면 「지난번엔 됐는데
-- 이번엔 왜」를 볼 수 없고, 두 번째 실행이 첫 번째 기록을 덮는다.
CREATE TABLE IF NOT EXISTS projmng.ai_task_run (
    run_key         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_key        bigint        NOT NULL REFERENCES projmng.ai_task (task_key),
    seq             int           NOT NULL DEFAULT 1,
    runner_key      bigint,
    run_status      varchar(20)   NOT NULL DEFAULT 'preparing',

    -- 임대. 실행기가 하트비트로 연장한다(문서 6.10)
    lease_expires_at timestamp,
    -- run 별 1회용 토큰의 해시. 배포 도구와 같은 방식이다(문서 6.9)
    token_hash      varchar(100),

    started_at      timestamp,
    finished_at     timestamp,
    exit_code       int,
    error_summary   varchar(1000),

    workspace_path  varchar(500),
    git_branch      varchar(200),
    -- 어느 커밋에서 갈라져 나왔나. 뒤처진 기준에서 돈 것을 나중에 알아보려면
    -- 이 값이 있어야 한다(문서 7.3)
    base_sha        varchar(64),
    diff_stat       varchar(500),
    log_line_count  int           NOT NULL DEFAULT 0,

    -- **AI 의 마지막 답.** 고친 내역일 수도, 물은 것의 답일 수도, 보고서일
    -- 수도 있다. 로그에서 가려내는 일을 화면과 메일이 각각 하지 않게
    -- 한 번 가려서 여기 적어 둔다(문서 4.2 · 8-2)
    result_text     text,

    cre_dt          timestamp     DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_ai_task_run_task
    ON projmng.ai_task_run (task_key, seq DESC);

-- ── 출력 줄 ──────────────────────────────────────────────────
--
-- 본문 행에 이어 붙이지 않는다. 목록 조회마다 수 MB 를 읽게 되고,
-- 실행 중 계속 커지는 값이라 매번 행 전체를 다시 쓰게 된다.
CREATE TABLE IF NOT EXISTS projmng.ai_task_log (
    log_key         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_key         bigint        NOT NULL REFERENCES projmng.ai_task_run (run_key),
    seq             int           NOT NULL,
    -- stdout · stderr · system · step
    stream          varchar(10)   NOT NULL DEFAULT 'stdout',
    log_text        text,
    log_at          timestamp     DEFAULT now()
);

-- 꼬리 읽기(fromSeq)가 타는 길. 같은 구간을 두 번 보내도 한 번만 들어가게
-- 유일 제약을 함께 건다(문서 10장).
CREATE UNIQUE INDEX IF NOT EXISTS ux_ai_task_log_seq
    ON projmng.ai_task_log (run_key, seq);

-- ── 실행 장비 ────────────────────────────────────────────────
--
-- 큐가 배달을 맡으므로 「어디로 줄까」를 고르는 표가 아니다.
-- **살아 있는지 보는 표**다(문서 6.12). 지금은 행이 하나다.
CREATE TABLE IF NOT EXISTS projmng.ai_runner (
    runner_key      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    runner_nm       varchar(100)  NOT NULL,
    host_nm         varchar(200),
    runner_kinds    varchar(100)  NOT NULL DEFAULT 'claude',
    -- 해시로만 둔다. 장비를 빼앗겼을 때 is_enabled 로 끊는다
    token_hash      varchar(100),
    max_parallel    int           NOT NULL DEFAULT 5,
    is_enabled      boolean       NOT NULL DEFAULT true,
    last_seen_at    timestamp,
    runner_version  varchar(50),
    cre_dt          timestamp     DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ai_runner_nm
    ON projmng.ai_runner (runner_nm);

-- ── 처음 한 번만: 기본 대상 ──────────────────────────────────
--
-- 운영 서버에 이미 clone 되어 있는 저장소다. 화면에서 바로 고를 수 있게
-- 한 줄 넣어 둔다. **push 는 꺼 둔 채로 시작한다** — 배포를 일으키는
-- 단추는 나머지가 검증된 뒤에 켠다(문서 16장 4단계).
INSERT INTO projmng.ai_target
    (target_nm, target_kind, target_path, repo_url, default_ref,
     isolation_mode, runner_kinds, allow_push, gate_mode, comments, cre_id)
SELECT 'Funeralv2 저장소', 'repo', '/home/lee/Funeralv2',
       'https://github.com/quristyle/Funeralv2.git', 'main',
       'worktree', 'claude,antigravity', false, 'build',
       '운영 서버의 정본 clone. worktree 로 격리해서 돈다.', 'system'
WHERE NOT EXISTS (
    SELECT 1 FROM projmng.ai_target WHERE target_path = '/home/lee/Funeralv2'
);

-- ── 이어가기 (설계 8-3) ─────────────────────────────────────
--
-- 끝난 작업에 「이어서」 지시할 수 있게 하는 값들이다.
--
-- **요약만으로는 절반이다.** 실행마다 worktree 를 새로 파면 두 번째 실행은
-- 지난 변경이 하나도 없는 자리에서 시작한다 — 요약에는 「고쳤다」고 적혀
-- 있는데 그 파일에는 그 변경이 없다. 그래서 작업이 **자기 작업공간과
-- 브랜치를 기억한다**(push 하지 않았으면 그것을 다시 쓴다).
--
-- 3단계에서 쓰기 시작하지만 칸은 지금 만들어 둔다 — 나중에 ALTER 를 운영에
-- 한 번 더 돌리는 것보다 낫다.

ALTER TABLE projmng.ai_task
    -- push 하지 않은 변경이 남아 있는 자리. 이어가기가 이것을 다시 쓴다.
    ADD COLUMN IF NOT EXISTS workspace_path varchar(500),
    ADD COLUMN IF NOT EXISTS git_branch     varchar(200),
    -- 몇 번째 왕복인가. 화면이 「3차」로 보여 준다.
    ADD COLUMN IF NOT EXISTS turn_no        int NOT NULL DEFAULT 0;

ALTER TABLE projmng.ai_task_run
    -- **그때 실제로 준 지시문.** 본문을 고쳐도 지난 실행이 무엇이었는지
    -- 남아야 한다 — 이것이 없으면 이력이 「결과만 있고 왜 그랬는지 없는」 꼴이 된다.
    ADD COLUMN IF NOT EXISTS instruction  text,
    -- 요약. 비면 result_text 를 쓴다(설계 8-3.4).
    ADD COLUMN IF NOT EXISTS summary_text text,
    -- CLI 의 대화 id. claude 는 --resume, agy 는 --conversation 이 받는다.
    -- **작업 폴더에 묶이므로** 같은 worktree 를 다시 쓸 때만 쓸모가 있다.
    ADD COLUMN IF NOT EXISTS session_id   varchar(100),
    ADD COLUMN IF NOT EXISTS session_kind varchar(20);
