-- ============================================================
-- 「AI 작업 요청」에 남길말을 주고받는다 (projmng 스키마)
-- ============================================================
--
-- 설계: docs/ai-task-runner.md · 화면
--   web/src/Apps/JSini.Web.ProjMng/Components/Pages/AiRequestList.razor
--   web/src/Apps/JSini.Web.ProjMng/Components/Shared/AiTaskNotes.razor
--
-- **EF 마이그레이션이 아니다.** ProjMngServer 는 Dapper + Npgsql 이라
-- 스키마를 SQL 파일이 만든다. 운영 반영은 손으로 한 번 돌린다.
--
--   psql -h … -U projmng -d projmng -f projmng-ai-task-note-2026-09-25.sql
--
-- 두 번 돌려도 안전하다.
--
-- ── 왜 표를 따로 두나 ───────────────────────────────────────
--
-- 일반 사용자가 올린 요청은 저장만 되고 아무 데서도 안 돈다. 관리자가
-- 그것을 읽고 **「이건 이렇게 하겠습니다」·「무엇을 더 알려 주십시오」**
-- 를 말할 자리가 없었다. 지시문(`ai_task.contents`)을 관리자가 고쳐 적는
-- 길은 두 가지가 한꺼번에 틀린다 — 올린 사람이 적은 글이 사라지고, 그
-- 글이 곧 AI 에게 갈 지시문이라 **대화가 지시에 섞여 들어간다.**
--
-- 그래서 지시문 옆에 오가는 말을 따로 쌓는다. 한 건에 여러 줄이 붙고
-- (관리자와 올린 사람이 번갈아 적는다) 순서가 뜻을 가지므로 칸이 아니라
-- 표다.
--
-- ── 「누가 적었나」를 칸으로 두지 않는다 ────────────────────
--
-- 관리자냐 요청자냐는 `cre_id` 와 `ai_task.cre_id` 를 견주면 나온다.
-- 별도 칸(`is_admin` 같은 것)을 두면 **적을 때의 역할**이 굳어, 나중에
-- 역할이 바뀌면 지난 줄이 거짓말을 한다. 조회가 조인 하나를 더 할 뿐이다.
--
-- ── `read_dt` 는 **요청자가 읽은 시각**이다 ─────────────────
--
-- 앱푸시를 받고 들어와 확인했는지를 화면이 배지로 세운다(「새 남긴말 2」).
-- 요청자가 스스로 적은 줄에는 처음부터 값이 있다 — 자기가 적은 것을
-- 자기에게 「안 읽음」으로 세울 이유가 없다.
CREATE TABLE IF NOT EXISTS projmng.ai_task_note (
    note_key   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 작업이 지워지면 함께 사라진다. 대화만 남아 봐야 가리킬 것이 없다.
    task_key   bigint    NOT NULL REFERENCES projmng.ai_task(task_key) ON DELETE CASCADE,

    contents   text      NOT NULL,

    -- 요청을 올린 사람이 이 줄을 확인한 시각. 널이면 아직 안 읽은 것이다.
    read_dt    timestamp NULL,

    -- 지운 줄도 자리는 남긴다 — 「무슨 말이 오갔나」의 번호가 어긋나면
    -- 뒤의 줄을 인용한 말이 가리킬 곳을 잃는다.
    is_deleted boolean   NOT NULL DEFAULT false,

    cre_id     varchar(50),
    cre_dt     timestamp DEFAULT now(),
    mod_id     varchar(50),
    mod_dt     timestamp
);

COMMENT ON TABLE  projmng.ai_task_note IS 'AI 작업 요청에 오가는 남길말. 관리자와 올린 사람이 번갈아 적는다.';
COMMENT ON COLUMN projmng.ai_task_note.task_key IS '어느 요청에 붙은 말인가.';
COMMENT ON COLUMN projmng.ai_task_note.read_dt  IS '요청을 올린 사람이 확인한 시각. 널이면 아직 안 읽었다.';

-- 화면이 언제나 **한 건의 말 전부**를 적은 순서대로 읽는다.
CREATE INDEX IF NOT EXISTS ix_ai_task_note_task
    ON projmng.ai_task_note (task_key, note_key)
 WHERE is_deleted = false;

-- 목록이 건마다 「안 읽은 말 몇 개」를 센다. 안 읽은 줄만 모아 두면
-- 다 읽은 건은 이 인덱스를 아예 타지 않는다.
CREATE INDEX IF NOT EXISTS ix_ai_task_note_unread
    ON projmng.ai_task_note (task_key)
 WHERE is_deleted = false AND read_dt IS NULL;

-- ── 확인 ─────────────────────────────────────────────────────
-- SELECT column_name, data_type
--   FROM information_schema.columns
--  WHERE table_schema = 'projmng' AND table_name = 'ai_task_note'
--  ORDER BY ordinal_position;
