-- ============================================================
-- 「빠른 지시」에 그림·파일을 같이 붙인다 (projmng 스키마)
-- ============================================================
--
-- 설계: docs/ai-task-runner.md · 화면
--   web/src/Apps/JSini.Web.ProjMng/Components/Shared/AiAskPanel.razor
--
-- **EF 마이그레이션이 아니다.** ProjMngServer 는 Dapper + Npgsql 이라
-- 스키마를 SQL 파일이 만든다. 운영 반영은 손으로 한 번 돌린다.
--
--   psql -h … -U projmng -d projmng -f projmng-ai-task-file-2026-09-25.sql
--
-- 두 번 돌려도 안전하다.
--
-- ── 왜 바이트를 DB 에 넣나 ──────────────────────────────────
--
-- 이 저장소에 첨부를 담는 자리가 이미 둘 있다. 둘 다 여기에는 안 맞는다.
--
--   · `InterfaceFileService` — ProjMngServer 컨테이너의 파일 시스템.
--     그 컨테이너에는 **붙은 디스크가 없다**(deploy/docker/docker-compose.prod.yml
--     의 projmng 는 appsettings 한 장만 마운트한다). 배포는 곧 새 컨테이너라
--     여기에 담으면 **다음 배포에 통째로 사라진다.**
--   · FileServer — 디스크(`/srv/jsini/files`)가 붙어 있어 살아남는다. 그런데
--     이 파일을 실제로 읽어야 하는 것은 **실행기**이고, 실행기가 아는 곳은
--     ProjMngServer 하나뿐이다(장비 토큰 · run 토큰). 게이트웨이를 거치게
--     하려면 실행기에 포털 계정을 쥐여 줘야 한다.
--
-- 그래서 `bytea` 다. 여기 담기는 것은 휴대폰으로 찍은 화면 사진 몇 장이고
-- 한 장 10MB · 한 건 5장으로 막는다(`AiTaskFileService`). 이 크기가 커지면
-- 그때 FileServer 로 옮기고 이 표에는 아이디만 남긴다.
--
-- ── `task_key` 가 널일 수 있는 까닭 ─────────────────────────
--
-- 「빠른 지시」는 **고르는 순간 올린다.** 글을 다 적고 단추를 누를 때까지
-- 기다리면 흔들리는 자리에서 사진 몇 장을 올리는 시간을 단추 뒤에 숨기게 되고,
-- 그 동안 화면은 아무 말도 못 한다. 그런데 그 시점에는 작업 번호가 아직 없다 —
-- 번호는 단추를 누를 때 생긴다.
--
-- 그래서 먼저 `task_key` 없이 담아 두고(「떠 있는 첨부」), 보낼 때 그 번호들을
-- 함께 실어 보내 묶는다. 묶이지 못한 것(적다가 그만둔 것)은 다음에 같은 사람이
-- 무언가를 올릴 때 하루 지난 것부터 치운다.
CREATE TABLE IF NOT EXISTS projmng.ai_task_file (
    file_key     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 널이면 **아직 안 묶인 것**이다. 위 머리말 참고.
    task_key     bigint       NULL REFERENCES projmng.ai_task(task_key) ON DELETE CASCADE,

    file_nm      varchar(200) NOT NULL,
    content_type varchar(150) NOT NULL DEFAULT 'application/octet-stream',
    byte_size    bigint       NOT NULL,
    content      bytea        NOT NULL,

    -- 화면이 미리보기를 그릴지 아이콘만 세울지 가르는 값. 내려받을 때의
    -- `Content-Type` 과 **따로 둔다** — 그쪽은 올라온 값을 그대로 믿지만
    -- 이 값은 서버가 판정한다.
    is_image     boolean      NOT NULL DEFAULT false,

    cre_id       varchar(50),
    cre_dt       timestamp    DEFAULT now()
);

COMMENT ON TABLE  projmng.ai_task_file IS 'AI 작업 지시에 함께 올린 그림·파일. 실행기가 받아 작업공간에 풀어 둔다.';
COMMENT ON COLUMN projmng.ai_task_file.task_key IS '묶인 작업. 널이면 아직 안 보낸 「떠 있는 첨부」다.';
COMMENT ON COLUMN projmng.ai_task_file.content  IS '파일 바이트. 컨테이너에 디스크가 없어 DB 에 담는다.';
COMMENT ON COLUMN projmng.ai_task_file.is_image IS '미리보기를 그릴 수 있는 그림인가. 서버가 판정한다.';

-- 상세 화면과 실행기가 **작업 하나의 첨부 전부**를 읽는다.
CREATE INDEX IF NOT EXISTS ix_ai_task_file_task
    ON projmng.ai_task_file (task_key, file_key)
 WHERE task_key IS NOT NULL;

-- 묶이지 못하고 남은 것을 치우는 조회가 이 길로 간다.
CREATE INDEX IF NOT EXISTS ix_ai_task_file_loose
    ON projmng.ai_task_file (cre_id, cre_dt)
 WHERE task_key IS NULL;

-- ── 확인 ─────────────────────────────────────────────────────
-- SELECT column_name, data_type
--   FROM information_schema.columns
--  WHERE table_schema = 'projmng' AND table_name = 'ai_task_file'
--  ORDER BY ordinal_position;
