-- ============================================================
-- 보고서 메일 배치 — 표 셋 (2026-10-10)
-- ============================================================
--
-- 화면: web/src/Apps/JSini.Web.Admin/Components/Pages/ReportMailList.razor
-- 메뉴: deploy/sql/report-mail-menu-2026-10-10.sql
-- 문서: docs/report-mail.md
--
--   psql -h … -U funeralv2 -d jsiniportal -f report-mail-2026-10-10.sql
--
-- EF 마이그레이션 `AddReportMailSchedules` 를 그대로 뽑은 것이다
-- (dotnet ef migrations script). **AuthServer 는 기동할 때 마이그레이션을
-- 돌리지 않으므로**(Database.Migrate() 는 FileServer 에만 있다) 이 DDL 을 손으로
-- 넣고 __EFMigrationsHistory 에 줄까지 넣어야 다음에 다시 돌지 않는다.
--
-- ── 시각 칸이 둘로 갈린다 ───────────────────────────────────
--
-- send_hour_kst · send_minute_kst 는 **한국 벽시계**다. 사람이 고른 것이
-- 「아침 여덟 시」라서고, 그 뜻을 UTC 로 적어 두면 설정 화면이 다시 아홉
-- 시간을 빼서 보여 줘야 한다. 실제로 보낸 순간(last_sent_at)은 다른 표와
-- 같이 timestamptz(UTC) 다 — docs/utc-time.md 의 「한국 시각으로 남은 자리」.
--
-- ── 보고서를 메뉴에 외래키로 걸지 않는다 ────────────────────
--
-- report_key 는 메뉴의 route_key 이지 기본키가 아니고, 메뉴를 지웠다고 배치가
-- 함께 사라지면 안 된다. 없어진 보고서는 화면이 「없어진 보고서」로 짚어 준다.
--
-- 두 번 돌리면 CREATE TABLE 에서 멈춘다(멱등이 아니다). 이미 넣었는지는
--   select * from scom."__EFMigrationsHistory" where "MigrationId" like '%ReportMail%';
-- 로 먼저 본다.
-- ============================================================

START TRANSACTION;
CREATE TABLE scom.report_mail_schedules (
    id text NOT NULL,
    name character varying(128) NOT NULL,
    frequency character varying(16) NOT NULL,
    day_of_week integer,
    day_of_month integer,
    send_hour_kst integer NOT NULL,
    send_minute_kst integer NOT NULL,
    is_active boolean NOT NULL,
    remark character varying(512),
    last_sent_at timestamp with time zone,
    last_result character varying(512),
    created_at timestamp with time zone NOT NULL,
    created_by text,
    updated_at timestamp with time zone,
    updated_by text,
    is_deleted boolean NOT NULL,
    CONSTRAINT "PK_report_mail_schedules" PRIMARY KEY (id)
);
COMMENT ON TABLE scom.report_mail_schedules IS '보고서 메일 배치 하나 — 어떤 보고서를 · 어느 역할에게 ·
             얼마나 자주 보낼지를 묶은 줄.';
COMMENT ON COLUMN scom.report_mail_schedules.name IS '배치 이름. 목록에서 사람이 알아보는 글자다';
COMMENT ON COLUMN scom.report_mail_schedules.frequency IS '주기. ReportMailFrequency 의 값 하나 — DAILY · WEEKDAY ·
            WEEKLY · MONTHLY.';
COMMENT ON COLUMN scom.report_mail_schedules.day_of_week IS '주간일 때 보낼 요일. 1(월) ~ 7(일) — ISO 순서다.
            다른 주기에서는 비어 있다.';
COMMENT ON COLUMN scom.report_mail_schedules.day_of_month IS '월간일 때 보낼 날. 1 ~ 31.
            그 달에 없는 날이면 말일에 보낸다(31 일을 고른 2월은 28·29일).';
COMMENT ON COLUMN scom.report_mail_schedules.send_hour_kst IS '보낼 시각(시). 한국 벽시계다 — 머리말 참고';
COMMENT ON COLUMN scom.report_mail_schedules.send_minute_kst IS '보낼 시각(분). 한국 벽시계다';
COMMENT ON COLUMN scom.report_mail_schedules.is_active IS '켜져 있나. 꺼 두면 발송기가 건너뛴다';
COMMENT ON COLUMN scom.report_mail_schedules.remark IS '메일 머리에 붙일 한마디. 비워도 된다';
COMMENT ON COLUMN scom.report_mail_schedules.last_sent_at IS '마지막으로 보낸 때 (UTC). 한 번도 안 보냈으면 비어 있다';
COMMENT ON COLUMN scom.report_mail_schedules.last_result IS '마지막 발송의 결과. 성공이면 받은 사람 수가, 실패면 까닭이 적힌다.';

CREATE TABLE scom.report_mail_schedule_reports (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    schedule_id character varying(64) NOT NULL,
    report_key character varying(128) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by text,
    updated_at timestamp with time zone,
    updated_by text,
    is_deleted boolean NOT NULL,
    CONSTRAINT "PK_report_mail_schedule_reports" PRIMARY KEY (id),
    CONSTRAINT "FK_report_mail_schedule_reports_report_mail_schedules_schedule~" FOREIGN KEY (schedule_id) REFERENCES scom.report_mail_schedules (id) ON DELETE CASCADE
);
COMMENT ON TABLE scom.report_mail_schedule_reports IS '배치가 고른 보고서 하나. 가리키는 값은 메뉴 열쇠(route_key)다.';
COMMENT ON COLUMN scom.report_mail_schedule_reports.schedule_id IS '어느 배치의 것인가';
COMMENT ON COLUMN scom.report_mail_schedule_reports.report_key IS '보고서 화면의 열쇠 (예: helpdesk.report.weekly)';

CREATE TABLE scom.report_mail_schedule_roles (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    schedule_id character varying(64) NOT NULL,
    role_id character varying(64) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by text,
    updated_at timestamp with time zone,
    updated_by text,
    is_deleted boolean NOT NULL,
    CONSTRAINT "PK_report_mail_schedule_roles" PRIMARY KEY (id),
    CONSTRAINT "FK_report_mail_schedule_roles_report_mail_schedules_schedule_id" FOREIGN KEY (schedule_id) REFERENCES scom.report_mail_schedules (id) ON DELETE CASCADE,
    CONSTRAINT "FK_report_mail_schedule_roles_roles_role_id" FOREIGN KEY (role_id) REFERENCES scom.roles (id) ON DELETE CASCADE
);
COMMENT ON TABLE scom.report_mail_schedule_roles IS '배치를 받을 역할 하나.';
COMMENT ON COLUMN scom.report_mail_schedule_roles.schedule_id IS '어느 배치의 것인가';
COMMENT ON COLUMN scom.report_mail_schedule_roles.role_id IS '역할 식별자 (scom.roles.id)';

CREATE UNIQUE INDEX "IX_report_mail_schedule_reports_schedule_id_report_key" ON scom.report_mail_schedule_reports (schedule_id, report_key);

CREATE INDEX "IX_report_mail_schedule_roles_role_id" ON scom.report_mail_schedule_roles (role_id);

CREATE UNIQUE INDEX "IX_report_mail_schedule_roles_schedule_id_role_id" ON scom.report_mail_schedule_roles (schedule_id, role_id);

CREATE INDEX "IX_report_mail_schedules_is_active" ON scom.report_mail_schedules (is_active);

INSERT INTO scom."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261009221407_AddReportMailSchedules', '10.0.11');

COMMIT;

