<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Funeralv2.Shared.Infrastructure</AssemblyName>
    <RootNamespace>Funeralv2.Shared.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Funeralv2.Shared.DTOs\Funeralv2.Shared.DTOs.csproj" />
  </ItemGroup>

</Project>
