<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>JSini.Shared.Infrastructure</AssemblyName>
    <RootNamespace>JSini.Shared.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JSini.Shared.DTOs\JSini.Shared.DTOs.csproj" />
  </ItemGroup>

</Project>
